"""Regenerates documentation files like FOLDER.md and index files."""

import os
from pathlib import Path
from typing import Optional, List, Dict
import structlog

from .base import BaseFixer

logger = structlog.get_logger()


class DocsRegenerator(BaseFixer):
    """Regenerates missing or outdated documentation files."""

    FOLDER_DOC_NAME = "FOLDER.md"
    INDEX_NAMES = ["index.md", "README.md"]

    def get_fix_type(self) -> str:
        return "docs_regen"

    def can_fix(self, file_path: Path) -> bool:
        """This fixer creates new files, not modifies existing ones."""
        return False

    def fix(self, file_path: Path, content: str) -> Optional[str]:
        """Not used - this fixer creates new files."""
        return None

    def find_directories_missing_folder_doc(self) -> List[Path]:
        """Find directories that should have FOLDER.md but don't."""
        missing = []

        for dirpath in self.repo_path.rglob("*"):
            if not dirpath.is_dir():
                continue

            # Skip common non-documentation directories
            skip_dirs = {
                "node_modules", "__pycache__", ".git", "venv", ".venv",
                "dist", "build", ".pytest_cache", ".mypy_cache", "coverage",
                ".next", ".nuxt", "out", "target", "vendor",
            }

            if any(skip in dirpath.parts for skip in skip_dirs):
                continue

            # Check if directory has code files
            has_code = any(
                f.suffix in {'.py', '.js', '.ts', '.tsx', '.jsx', '.go', '.rs', '.java'}
                for f in dirpath.iterdir()
                if f.is_file()
            )

            if not has_code:
                continue

            # Check if FOLDER.md exists
            folder_doc = dirpath / self.FOLDER_DOC_NAME
            if not folder_doc.exists():
                missing.append(dirpath)

        return missing

    def generate_folder_doc(self, directory: Path) -> str:
        """Generate FOLDER.md content for a directory."""
        # Analyze directory contents
        files = []
        subdirs = []

        for item in sorted(directory.iterdir()):
            if item.name.startswith('.'):
                continue

            if item.is_file():
                files.append(item)
            elif item.is_dir():
                subdirs.append(item)

        # Get relative path from repo root
        try:
            rel_path = directory.relative_to(self.repo_path)
            dir_name = str(rel_path).replace('/', ' > ')
        except ValueError:
            dir_name = directory.name

        # Build documentation
        lines = [
            f"# {directory.name}",
            "",
            f"**Location:** `{rel_path}`",
            "",
            "## Overview",
            "",
            f"This directory contains {len(files)} files and {len(subdirs)} subdirectories.",
            "",
        ]

        # List files by type
        if files:
            files_by_ext = {}
            for f in files:
                ext = f.suffix or "no extension"
                if ext not in files_by_ext:
                    files_by_ext[ext] = []
                files_by_ext[ext].append(f)

            lines.append("## Files")
            lines.append("")

            for ext in sorted(files_by_ext.keys()):
                file_list = files_by_ext[ext]
                lines.append(f"### {ext}")
                lines.append("")
                for f in sorted(file_list):
                    # Try to extract first docstring/comment
                    purpose = self._extract_file_purpose(f)
                    if purpose:
                        lines.append(f"- `{f.name}` - {purpose}")
                    else:
                        lines.append(f"- `{f.name}`")
                lines.append("")

        # List subdirectories
        if subdirs:
            lines.append("## Subdirectories")
            lines.append("")
            for d in sorted(subdirs):
                lines.append(f"- `{d.name}/`")
            lines.append("")

        lines.extend([
            "---",
            "",
            "*This file was auto-generated by Aethyme Autofixer.*",
        ])

        return "\n".join(lines)

    def _extract_file_purpose(self, file_path: Path) -> Optional[str]:
        """Extract first comment/docstring from file."""
        try:
            with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                lines = [f.readline() for _ in range(20)]  # First 20 lines

            content = ''.join(lines)

            # Python docstring
            if file_path.suffix == '.py':
                # Look for module docstring
                import re
                match = re.search(r'"""(.*?)"""', content, re.DOTALL)
                if match:
                    doc = match.group(1).strip()
                    return doc.split('\n')[0][:100]

                match = re.search(r"'''(.*?)'''", content, re.DOTALL)
                if match:
                    doc = match.group(1).strip()
                    return doc.split('\n')[0][:100]

            # JavaScript/TypeScript comment
            if file_path.suffix in {'.js', '.ts', '.tsx', '.jsx'}:
                import re
                match = re.search(r'/\*\*(.*?)\*/', content, re.DOTALL)
                if match:
                    doc = match.group(1).strip()
                    # Remove leading * from each line
                    doc = '\n'.join(
                        line.strip().lstrip('*').strip()
                        for line in doc.split('\n')
                    )
                    return doc.split('\n')[0][:100]

        except Exception:
            pass

        return None

    def create_folder_docs(self) -> List[Dict[str, any]]:
        """Create FOLDER.md files for directories missing them."""
        missing_dirs = self.find_directories_missing_folder_doc()
        created = []

        for directory in missing_dirs:
            try:
                content = self.generate_folder_doc(directory)
                doc_path = directory / self.FOLDER_DOC_NAME

                created.append({
                    "file_path": doc_path,
                    "original_content": "",  # New file
                    "new_content": content,
                    "fix_type": self.get_fix_type(),
                })

                self.fixes_applied += 1
                logger.info("Generated FOLDER.md", directory=str(directory))

            except Exception as e:
                error_msg = f"Failed to create FOLDER.md in {directory}: {e}"
                self.errors.append(error_msg)
                logger.error("FOLDER.md creation failed", directory=str(directory), error=str(e))

        self.files_processed = len(missing_dirs)
        return created

    def update_existing_folder_docs(self) -> List[Dict[str, any]]:
        """Update existing FOLDER.md files with fresh content."""
        updated = []

        for doc_path in self.repo_path.rglob(self.FOLDER_DOC_NAME):
            try:
                directory = doc_path.parent

                with open(doc_path, 'r', encoding='utf-8') as f:
                    original_content = f.read()

                new_content = self.generate_folder_doc(directory)

                if new_content != original_content:
                    updated.append({
                        "file_path": doc_path,
                        "original_content": original_content,
                        "new_content": new_content,
                        "fix_type": self.get_fix_type(),
                    })

                    logger.info("Updated FOLDER.md", path=str(doc_path))

            except Exception as e:
                error_msg = f"Failed to update {doc_path}: {e}"
                self.errors.append(error_msg)
                logger.error("FOLDER.md update failed", path=str(doc_path), error=str(e))

        return updated
