"""Tests for enhancement deployment and generated onboarding artifacts."""

from __future__ import annotations

import json
import os
from pathlib import Path

from src.enhance import AGENTS_OVERRIDE_PATH, deploy, is_ok, verify
from tests.support.cli_invoke import invoke_aethyme

# CWD-independent package root (tests run with cwd=packages/aethyme in CI,
# but repo-root-relative paths broke when invoked from elsewhere).
_PACKAGE_ROOT = Path(__file__).resolve().parents[2]


def _build_repo(root: Path) -> None:
    root.mkdir(parents=True, exist_ok=True)
    (root / "package.json").write_text(
        '{"name":"demo","scripts":{"test":"vitest","dev":"vite","build":"vite build"}}\n',
        encoding="utf-8",
    )
    (root / "pnpm-lock.yaml").write_text("lockfileVersion: '9.0'\n", encoding="utf-8")
    (root / "src").mkdir(exist_ok=True)
    (root / "src" / "main.ts").write_text("console.log('demo')\n", encoding="utf-8")


def test_agents_document_includes_broker_protocol_only_when_configured(
    tmp_path: Path,
) -> None:
    repo_path = tmp_path / "demo-repo"
    _build_repo(repo_path)

    # No broker config → no broker section, no failing instructions.
    deploy(repo_path)
    agents_text = (repo_path / "AGENTS.md").read_text(encoding="utf-8")
    assert "Broker Coordination" not in agents_text

    # Broker-configured repo → the protocol appears, with the essentials:
    # status-before-editing, submit-not-merge, the action-required file,
    # and the never-touch-integration rule.
    (repo_path / ".aethyme").mkdir(exist_ok=True)
    (repo_path / ".aethyme/gates.toml").write_text(
        '[[gate]]\nname = "ok"\ncommand = "true"\n', encoding="utf-8"
    )
    deploy(repo_path, force=True)
    agents_text = (repo_path / "AGENTS.md").read_text(encoding="utf-8")
    assert "## Broker Coordination" in agents_text
    assert "broker status --json" in agents_text
    assert "broker start --task" in agents_text
    assert "broker adopt" in agents_text
    assert "broker leases claim" in agents_text
    assert "broker exec --session" in agents_text
    assert "broker submit" in agents_text
    assert "AETHYME_TEST_DB_SUFFIX" in agents_text
    assert ".aethyme/broker-action-required.md" in agents_text
    assert "aethyme/integration" in agents_text
    # CLAUDE.md renders from the same generated document.
    claude_text = (repo_path / "CLAUDE.md").read_text(encoding="utf-8")
    assert "## Broker Coordination" in claude_text


def test_enhance_deploy_writes_generated_onboarding(tmp_path: Path) -> None:
    repo_path = tmp_path / "demo-repo"
    _build_repo(repo_path)

    actions = deploy(repo_path)
    written = {action.target.relative_path for action in actions}

    assert ".codex/skills/aethyme/SKILL.md" in written
    assert "AGENTS.md" in written
    assert ".codex/skills/repo-onboarding/SKILL.md" in written
    assert ".claude/skills/repo-onboarding/SKILL.md" in written
    assert ".codex/skills/repo-act/SKILL.md" in written
    assert ".claude/skills/repo-act/SKILL.md" in written
    assert ".aethyme/generated/onboarding.json" in written
    assert ".aethyme/generated/act-starter.json" in written

    artifact = json.loads((repo_path / ".aethyme/generated/onboarding.json").read_text(encoding="utf-8"))
    act_artifact = json.loads((repo_path / ".aethyme/generated/act-starter.json").read_text(encoding="utf-8"))
    telemetry_lines = (repo_path / ".aethyme/generated/experience-telemetry.jsonl").read_text(
        encoding="utf-8"
    ).splitlines()
    assert artifact["telemetry"]["counts"]["commands"] >= 1
    assert artifact["summon"]["task_signals"]
    assert act_artifact["starter_checklists"]["debugging"]
    assert any(json.loads(line)["event_type"] == "enhance.deploy" for line in telemetry_lines)

    results = verify(repo_path)
    assert is_ok(results)

    wrapper_text = (repo_path / ".claude" / "hooks" / "aethyme-load-context.sh").read_text(
        encoding="utf-8"
    )
    assert "repo record-wrapper-invocation" in wrapper_text
    assert "--wrapper aethyme-sessionstart-hook" in wrapper_text

    agents_text = (repo_path / "AGENTS.md").read_text(encoding="utf-8")
    assert "This file is generated by Aethyme. Do not edit it directly." in agents_text
    assert "python -m src.cli explore" in agents_text
    assert "Do not run `python -m src.cli explore`" in agents_text
    assert "## Aethyme Repo Routing" in agents_text
    assert "Primary fast test: `pnpm test`" in agents_text
    assert "Primary app entrypoint: `src/main.ts`" in agents_text
    assert ".aethyme/generated/experience-status.md" in agents_text
    assert "## Commit Hygiene" in agents_text
    assert "repo lint-commit-message .git/COMMIT_EDITMSG" in agents_text


def test_enhance_deploy_migrates_human_agents_content_into_override(tmp_path: Path) -> None:
    repo_path = tmp_path / "demo-repo"
    _build_repo(repo_path)
    (repo_path / "AGENTS.md").write_text(
        "# Maintainer Rules\n\nRun focused tests before broad suites.\n",
        encoding="utf-8",
    )

    deploy(repo_path)
    first_text = (repo_path / "AGENTS.md").read_text(encoding="utf-8")
    override_payload = json.loads((repo_path / AGENTS_OVERRIDE_PATH).read_text(encoding="utf-8"))
    assert override_payload["maintainer_markdown"] == (
        "# Maintainer Rules\n\nRun focused tests before broad suites."
    )
    assert "## Maintainer Notes" in first_text
    assert "# Maintainer Rules" in first_text
    assert "Run focused tests before broad suites." in first_text

    deploy(repo_path, force=True)
    second_text = (repo_path / "AGENTS.md").read_text(encoding="utf-8")
    assert "<!-- AETHYME:BEGIN generated -->" not in second_text
    assert "# Maintainer Rules" in second_text
    assert "## Aethyme Repo Routing" in second_text


def test_enhance_deploy_migrates_old_full_file_agents_template(tmp_path: Path) -> None:
    repo_path = tmp_path / "demo-repo"
    _build_repo(repo_path)
    template = (_PACKAGE_ROOT / "skills/aethyme/AGENTS.md").read_text(
        encoding="utf-8"
    )
    rendered = template.replace(
        "{{AETHYME_ROOT}}",
        str(_PACKAGE_ROOT),
    )
    (repo_path / "AGENTS.md").write_text(rendered, encoding="utf-8")

    deploy(repo_path)
    agents_text = (repo_path / "AGENTS.md").read_text(encoding="utf-8")
    assert agents_text.startswith("# Agent Instructions")
    assert agents_text.count("# Agent Instructions") == 1
    assert "<!-- AETHYME:BEGIN generated -->" not in agents_text


def test_init_and_validate_onboarding_overrides_cli(tmp_path: Path) -> None:
    repo_path = tmp_path / "demo-repo"
    _build_repo(repo_path)

    init_result = invoke_aethyme(["repo", "init-onboarding-overrides", str(repo_path)])
    assert init_result.exit_code == 0, init_result.output
    assert (repo_path / ".aethyme" / "overrides" / "onboarding.json").exists()

    validate_result = invoke_aethyme(["repo", "validate-onboarding-overrides", str(repo_path)])
    assert validate_result.exit_code == 0, validate_result.output
    assert "Valid override file" in validate_result.output
    telemetry_lines = (repo_path / ".aethyme/generated/experience-telemetry.jsonl").read_text(
        encoding="utf-8"
    ).splitlines()
    event_types = [json.loads(line)["event_type"] for line in telemetry_lines]
    assert "repo.init-onboarding-overrides" in event_types
    assert "repo.validate-onboarding-overrides" in event_types


def test_init_and_validate_agents_overrides_cli(tmp_path: Path) -> None:
    repo_path = tmp_path / "demo-repo"
    _build_repo(repo_path)

    init_result = invoke_aethyme(["repo", "init-agents-overrides", str(repo_path)])
    assert init_result.exit_code == 0, init_result.output
    assert (repo_path / AGENTS_OVERRIDE_PATH).exists()

    validate_result = invoke_aethyme(["repo", "validate-agents-overrides", str(repo_path)])
    assert validate_result.exit_code == 0, validate_result.output
    assert "Valid override file" in validate_result.output
    telemetry_lines = (repo_path / ".aethyme/generated/experience-telemetry.jsonl").read_text(
        encoding="utf-8"
    ).splitlines()
    event_types = [json.loads(line)["event_type"] for line in telemetry_lines]
    assert "repo.init-agents-overrides" in event_types
    assert "repo.validate-agents-overrides" in event_types


def test_enhance_verify_prints_summary(tmp_path: Path) -> None:
    repo_path = tmp_path / "demo-repo"
    _build_repo(repo_path)
    deploy(repo_path)

    result = invoke_aethyme(["enhance", "verify", "--repo", str(repo_path)])
    assert result.exit_code == 0, result.output
    assert "Enhancement summary:" in result.output
    assert "Recommendation: load `repo-onboarding` then run `explore`" in result.output
    assert "Experience telemetry:" in result.output
    telemetry_lines = (repo_path / ".aethyme/generated/experience-telemetry.jsonl").read_text(
        encoding="utf-8"
    ).splitlines()
    assert any(json.loads(line)["event_type"] == "enhance.verify" for line in telemetry_lines)


def test_static_wrapper_template_records_invocation_signal() -> None:
    wrapper_text = (
        (_PACKAGE_ROOT / "skills/aethyme/aethyme-explore")
        .read_text(encoding="utf-8")
    )
    assert "repo record-wrapper-invocation" in wrapper_text
    assert "--wrapper aethyme-explore" in wrapper_text


def test_repo_experience_telemetry_reports_json_and_text(tmp_path: Path) -> None:
    repo_path = tmp_path / "demo-repo"
    _build_repo(repo_path)
    deploy(repo_path)

    invoke_aethyme([
            "repo",
            "record-wrapper-invocation",
            str(repo_path),
            "--wrapper",
            "aethyme-explore",
            "--detail",
            "source=test",
        ])

    json_result = invoke_aethyme(["repo", "experience-telemetry", str(repo_path), "--json-output"])
    assert json_result.exit_code == 0, json_result.output
    payload = json.loads(json_result.output)
    assert payload["event_count"] >= 2
    assert payload["wrapper_invocations"]["aethyme-explore"] >= 1
    assert "enhance.deploy" in payload["by_type"]
    assert payload["kpis"]["wrapper_total"] >= 1
    assert payload["kpis"]["act_has_fast_test"] is True

    text_result = invoke_aethyme(["repo", "experience-telemetry", str(repo_path)])
    assert text_result.exit_code == 0, text_result.output
    assert "Wrapper invocations:" in text_result.output
    assert "KPIs:" in text_result.output
    assert "aethyme-explore" in text_result.output


def test_repo_experience_status_writes_artifacts(tmp_path: Path) -> None:
    repo_path = tmp_path / "demo-repo"
    _build_repo(repo_path)
    deploy(repo_path)

    result = invoke_aethyme(["repo", "experience-status", str(repo_path), "--json-output"])
    assert result.exit_code == 0, result.output
    payload = json.loads(result.output)
    assert payload["schema_version"] == "aethyme-experience-status-v1"
    assert "recommended_next_action" in payload
    assert (repo_path / ".aethyme" / "generated" / "experience-status.json").exists()
    assert (repo_path / ".aethyme" / "generated" / "experience-status.md").exists()

    markdown = (repo_path / ".aethyme" / "generated" / "experience-status.md").read_text(
        encoding="utf-8"
    )
    assert "# Aethyme Experience Status" in markdown
    assert "Recommended Next Action" in markdown


def test_repo_experience_telemetry_flags_no_wrapper_usage(tmp_path: Path) -> None:
    repo_path = tmp_path / "demo-repo"
    _build_repo(repo_path)
    deploy(repo_path)

    result = invoke_aethyme(["repo", "experience-telemetry", str(repo_path), "--json-output"])
    assert result.exit_code == 0, result.output
    payload = json.loads(result.output)
    codes = [signal["code"] for signal in payload["kpis"]["signals"]]
    assert "enhanced_but_no_wrapper_usage" in codes
    suggestion_codes = [suggestion["code"] for suggestion in payload["kpis"]["suggestions"]]
    assert "load_onboarding_and_use_wrapper" in suggestion_codes

    text_result = invoke_aethyme(["repo", "experience-telemetry", str(repo_path)])
    assert text_result.exit_code == 0, text_result.output
    assert "Suggestions:" in text_result.output
    assert "load_onboarding_and_use_wrapper" in text_result.output

    check_result = invoke_aethyme(["repo", "experience-telemetry", str(repo_path), "--check"])
    assert check_result.exit_code == 1, check_result.output


def test_repo_experience_telemetry_detects_stale_override_artifacts(tmp_path: Path) -> None:
    repo_path = tmp_path / "demo-repo"
    _build_repo(repo_path)
    deploy(repo_path)

    override_path = repo_path / ".aethyme" / "overrides" / "onboarding.json"
    override_path.parent.mkdir(parents=True, exist_ok=True)
    override_path.write_text(
        json.dumps(
            {
                "notes": ["Local maintainer hint"],
                "commands": [
                    {
                        "kind": "test",
                        "command": "./scripts/test-fast.sh",
                        "source": "manual-override",
                        "confidence": "high",
                    }
                ],
            }
        )
        + "\n",
        encoding="utf-8",
    )
    onboarding_path = repo_path / ".aethyme" / "generated" / "onboarding.json"
    act_path = repo_path / ".aethyme" / "generated" / "act-starter.json"
    newer_mtime = max(onboarding_path.stat().st_mtime, act_path.stat().st_mtime) + 5
    os.utime(override_path, (newer_mtime, newer_mtime))

    result = invoke_aethyme(["repo", "experience-telemetry", str(repo_path), "--json-output"])
    assert result.exit_code == 0, result.output
    payload = json.loads(result.output)
    codes = [signal["code"] for signal in payload["kpis"]["signals"]]
    assert "override_regeneration_required" in codes
    assert payload["freshness"]["regeneration_required"] is True
    assert set(payload["freshness"]["stale_targets"]) == {"onboarding", "act"}
    suggestion_codes = [suggestion["code"] for suggestion in payload["kpis"]["suggestions"]]
    assert "regenerate_onboarding_artifacts" in suggestion_codes

    text_result = invoke_aethyme(["repo", "experience-telemetry", str(repo_path)])
    assert text_result.exit_code == 0, text_result.output
    assert "Override freshness:" in text_result.output
    assert "regeneration_required: yes" in text_result.output

    check_result = invoke_aethyme(["repo", "experience-telemetry", str(repo_path), "--check"])
    assert check_result.exit_code == 1, check_result.output


def test_enhance_verify_refreshes_experience_status(tmp_path: Path) -> None:
    repo_path = tmp_path / "demo-repo"
    _build_repo(repo_path)
    deploy(repo_path)

    result = invoke_aethyme(["enhance", "verify", "--repo", str(repo_path)])
    assert result.exit_code == 0, result.output
    assert "Experience status:" in result.output

    status_json = repo_path / ".aethyme" / "generated" / "experience-status.json"
    status_markdown = repo_path / ".aethyme" / "generated" / "experience-status.md"
    assert status_json.exists()
    assert status_markdown.exists()

    payload = json.loads(status_json.read_text(encoding="utf-8"))
    assert payload["recommended_next_action"]["command"]


def test_enhance_verify_fails_on_direct_agents_edit(tmp_path: Path) -> None:
    repo_path = tmp_path / "demo-repo"
    _build_repo(repo_path)
    deploy(repo_path)

    agents_path = repo_path / "AGENTS.md"
    agents_path.write_text(
        agents_path.read_text(encoding="utf-8") + "\n\nManual direct edit.\n",
        encoding="utf-8",
    )

    result = invoke_aethyme(["enhance", "verify", "--repo", str(repo_path)])
    assert result.exit_code == 1, result.output
    assert "AGENTS.md" in result.output
    assert "direct edits unsupported; use .aethyme/overrides/agents.json" in result.output
