"""README Generator Service.

Auto-generate comprehensive README files from repository analysis:
- Project description from git metadata
- Installation instructions
- Usage examples from code
- API documentation
- Contributing guidelines
"""

from typing import Dict, Any, List, Optional
from datetime import datetime


class READMEGenerator:
    """Generate README.md files from repository analysis."""

    def __init__(self, repository_id: str, repository_name: str):
        """Initialize README generator.

        Args:
            repository_id: Repository ID
            repository_name: Repository name (e.g., "owner/repo")
        """
        self.repository_id = repository_id
        self.repository_name = repository_name

    def generate(
        self,
        description: Optional[str] = None,
        language: str = "unknown",
        api_docs: Optional[Dict[str, Any]] = None,
        metrics: Optional[Dict[str, Any]] = None,
        dependencies: Optional[List[str]] = None,
    ) -> str:
        """Generate complete README.md content.

        Args:
            description: Project description
            language: Primary programming language
            api_docs: API documentation structure
            metrics: Code metrics
            dependencies: List of dependencies

        Returns:
            Complete README.md content
        """
        sections = []

        # Header
        sections.append(self._generate_header())

        # Badges
        sections.append(self._generate_badges(language, metrics))

        # Description
        sections.append(self._generate_description(description, language))

        # Table of Contents
        sections.append(self._generate_toc())

        # Features
        sections.append(self._generate_features(api_docs))

        # Installation
        sections.append(self._generate_installation(language, dependencies))

        # Usage
        sections.append(self._generate_usage(language, api_docs))

        # API Reference
        if api_docs:
            sections.append(self._generate_api_reference(api_docs))

        # Code Quality
        if metrics:
            sections.append(self._generate_code_quality(metrics))

        # Contributing
        sections.append(self._generate_contributing())

        # License
        sections.append(self._generate_license())

        return "\n\n".join(sections)

    def _generate_header(self) -> str:
        """Generate README header with title."""
        repo_name = self.repository_name.split("/")[-1]
        return f"# {repo_name}"

    def _generate_badges(
        self, language: str, metrics: Optional[Dict[str, Any]]
    ) -> str:
        """Generate status badges."""
        badges = []

        # Language badge
        if language != "unknown":
            badges.append(
                f"![Language](https://img.shields.io/badge/language-{language}-blue)"
            )

        # Health score badge (if metrics available)
        if metrics and "summary" in metrics:
            health_score = metrics["summary"].get("health_score", 0)
            color = "green" if health_score >= 70 else "yellow" if health_score >= 50 else "red"
            badges.append(
                f"![Health Score](https://img.shields.io/badge/health-{health_score}%25-{color})"
            )

        # Documentation coverage badge
        if metrics and "quality" in metrics:
            doc_coverage = metrics["quality"].get("documentation_coverage", 0)
            color = "green" if doc_coverage >= 70 else "yellow" if doc_coverage >= 50 else "red"
            badges.append(
                f"![Docs](https://img.shields.io/badge/docs-{doc_coverage}%25-{color})"
            )

        return " ".join(badges) if badges else "<!-- Badges -->"

    def _generate_description(
        self, description: Optional[str], language: str
    ) -> str:
        """Generate project description."""
        if description:
            return description

        # Generate generic description
        repo_name = self.repository_name.split("/")[-1]
        return (
            f"**{repo_name}** is a {language} project. "
            "This README was automatically generated by Aethyme."
        )

    def _generate_toc(self) -> str:
        """Generate table of contents."""
        return """## Table of Contents

- [Features](#features)
- [Installation](#installation)
- [Usage](#usage)
- [API Reference](#api-reference)
- [Code Quality](#code-quality)
- [Contributing](#contributing)
- [License](#license)"""

    def _generate_features(self, api_docs: Optional[Dict[str, Any]]) -> str:
        """Generate features section."""
        features = ["## Features\n"]

        if api_docs and "files" in api_docs:
            # Extract features from API docs
            function_count = sum(
                len(file["functions"]) for file in api_docs["files"]
            )
            class_count = sum(len(file["classes"]) for file in api_docs["files"])

            if function_count > 0:
                features.append(f"- **{function_count} Functions** - Comprehensive API")
            if class_count > 0:
                features.append(f"- **{class_count} Classes** - Object-oriented design")

        if len(features) == 1:
            # No specific features found
            features.append("- Feature documentation coming soon")

        return "\n".join(features)

    def _generate_installation(
        self, language: str, dependencies: Optional[List[str]]
    ) -> str:
        """Generate installation instructions."""
        sections = ["## Installation\n"]

        if language == "go":
            sections.append("```bash")
            sections.append("go get " + self.repository_name)
            sections.append("```")
        elif language == "python":
            sections.append("```bash")
            sections.append("pip install " + self.repository_name.split("/")[-1])
            sections.append("```")
        elif language in ("javascript", "typescript"):
            sections.append("```bash")
            sections.append("npm install " + self.repository_name.split("/")[-1])
            sections.append("# or")
            sections.append("yarn add " + self.repository_name.split("/")[-1])
            sections.append("```")
        elif language == "rust":
            sections.append("Add to your `Cargo.toml`:")
            sections.append("\n```toml")
            sections.append("[dependencies]")
            sections.append(f'{self.repository_name.split("/")[-1]} = "0.1.0"')
            sections.append("```")
        else:
            sections.append("```bash")
            sections.append("# Clone the repository")
            sections.append(f"git clone https://github.com/{self.repository_name}")
            sections.append("```")

        # Add dependencies if available
        if dependencies:
            sections.append("\n### Dependencies\n")
            for dep in dependencies[:10]:  # Limit to 10
                sections.append(f"- {dep}")

        return "\n".join(sections)

    def _generate_usage(
        self, language: str, api_docs: Optional[Dict[str, Any]]
    ) -> str:
        """Generate usage examples."""
        sections = ["## Usage\n"]

        if api_docs and "files" in api_docs and api_docs["files"]:
            # Find first public function for example
            for file in api_docs["files"]:
                public_funcs = [
                    f for f in file.get("functions", []) if f["visibility"] == "public"
                ]
                if public_funcs:
                    func = public_funcs[0]

                    sections.append("### Basic Example\n")
                    sections.append(f"```{language}")

                    if language == "go":
                        sections.append(f'import "{self.repository_name}"\n')
                        params = ", ".join(
                            [f'{p["name"]}' for p in func.get("parameters", [])]
                        )
                        sections.append(f'result := {func["name"]}({params})')
                    elif language == "python":
                        sections.append(
                            f'from {self.repository_name.split("/")[-1]} import {func["name"]}\n'
                        )
                        params = ", ".join(
                            [f'{p["name"]}' for p in func.get("parameters", [])]
                        )
                        sections.append(f'result = {func["name"]}({params})')
                    elif language in ("javascript", "typescript"):
                        sections.append(
                            f'const {{ {func["name"]} }} = require("{self.repository_name.split("/")[-1]}");\n'
                        )
                        params = ", ".join(
                            [f'{p["name"]}' for p in func.get("parameters", [])]
                        )
                        sections.append(f'const result = {func["name"]}({params});')

                    sections.append("```")
                    break

        if len(sections) == 1:
            # No examples generated
            sections.append("```" + language)
            sections.append("// Usage examples coming soon")
            sections.append("```")

        return "\n".join(sections)

    def _generate_api_reference(self, api_docs: Dict[str, Any]) -> str:
        """Generate API reference section."""
        sections = ["## API Reference\n"]

        stats = api_docs.get("statistics", {})
        sections.append(
            f"This project provides **{stats.get('total_functions', 0)} functions** "
            f"and **{stats.get('total_classes', 0)} classes**.\n"
        )

        sections.append(
            "For detailed API documentation, see the [full API docs](./docs/API.md)."
        )

        return "\n".join(sections)

    def _generate_code_quality(self, metrics: Dict[str, Any]) -> str:
        """Generate code quality section."""
        sections = ["## Code Quality\n"]

        summary = metrics.get("summary", {})
        complexity = metrics.get("complexity", {})
        maintainability = metrics.get("maintainability", {})

        # Health score
        health_score = summary.get("health_score", 0)
        sections.append(f"**Health Score**: {health_score}/100\n")

        # Complexity
        avg_complexity = complexity.get("average_complexity", 0)
        sections.append("### Complexity Metrics\n")
        sections.append(f"- Average Cyclomatic Complexity: {avg_complexity}")
        sections.append(
            f"- High Complexity Functions: {complexity.get('high_complexity_count', 0)}"
        )

        # Maintainability
        mi = maintainability.get("maintainability_index", 0)
        sections.append("\n### Maintainability\n")
        sections.append(f"- Maintainability Index: {mi}/100")
        sections.append(
            f"- Technical Debt: {maintainability.get('technical_debt_minutes', 0)} minutes"
        )

        return "\n".join(sections)

    def _generate_contributing(self) -> str:
        """Generate contributing guidelines."""
        return """## Contributing

Contributions are welcome! Please follow these steps:

1. Fork the repository
2. Create a feature branch (`git checkout -b feature/amazing-feature`)
3. Commit your changes (`git commit -m 'Add amazing feature'`)
4. Push to the branch (`git push origin feature/amazing-feature`)
5. Open a Pull Request

Please ensure your code:
- Follows the existing code style
- Includes appropriate tests
- Updates documentation as needed"""

    def _generate_license(self) -> str:
        """Generate license section."""
        return """## License

This project is licensed under the MIT License - see the LICENSE file for details.

---

*This README was automatically generated by [Aethyme](https://aethyme.com)*"""
