"""Detector for edits to generated files."""

import re

from ..models import Finding, Severity
from .base import BaseDetector


class GeneratedFilesDetector(BaseDetector):
    """Detect manual edits to generated files."""

    @property
    def name(self) -> str:
        return "generated-files"

    @property
    def description(self) -> str:
        return "Checks for manual edits to auto-generated files"

    def detect(self) -> list[Finding]:
        """Detect files that appear to be generated but modified."""
        findings: list[Finding] = []

        # Generated file indicators
        generated_indicators = [
            r'@generated',
            r'AUTO-?GENERATED',
            r'DO NOT EDIT',
            r'This file is automatically generated',
            r'Code generated by',
            r'Generated by:',
            r'autogenerated',
            r'<auto-generated',
        ]

        # Generated file patterns
        generated_patterns = [
            r'\.g\.dart$',
            r'\.generated\.(ts|js)$',
            r'_pb2\.py$',  # Protocol buffers
            r'\.pb\.go$',
            r'migrations/versions/.*\.py$',  # DB migrations are generated
        ]

        # Scan all code files
        extensions = {'.py', '.ts', '.tsx', '.jsx', '.js', '.dart', '.go', '.java'}

        for file_path in self.repo_path.rglob('*'):
            if not file_path.is_file() or file_path.suffix not in extensions:
                continue

            if self.should_skip_file(file_path):
                continue

            # Check if filename matches generated pattern
            is_generated_name = any(re.search(pattern, str(file_path)) for pattern in generated_patterns)

            content = self.read_file_safe(file_path)
            if not content:
                continue

            # Check for generated indicators in first 20 lines
            lines = content.split('\n')
            header_lines = lines[:20]
            header_text = '\n'.join(header_lines)

            has_generated_marker = any(
                re.search(indicator, header_text, re.IGNORECASE)
                for indicator in generated_indicators
            )

            if is_generated_name or has_generated_marker:
                # Check if file has been modified (heuristic: has non-comment custom code)
                # This is a simplified check - could be enhanced with git history
                for _line_num, line in enumerate(lines[20:], start=21):  # Skip header
                    line_stripped = line.strip()
                    if not line_stripped or line_stripped.startswith(('#', '//', '/*', '*')):
                        continue

                    # If we find substantive code, might be custom
                    if len(line_stripped) > 10:
                        break

                if has_generated_marker:
                    findings.append(Finding(
                        detector=self.name,
                        severity=Severity.BLOCKER,
                        message="File marked as generated - manual edits will be overwritten",
                        file_path=str(file_path.relative_to(self.repo_path)),
                        line_number=None,
                        evidence=f"File contains: {next((i for i in generated_indicators if re.search(i, header_text, re.IGNORECASE)), 'generated marker')}",
                        suggestion="Do not edit generated files. Modify the template/generator instead."
                    ))

        return findings
