/**
 * RepoGraph Scorecard GitHub Action
 *
 * Runs AI-readiness scorecard on the repository and posts results to PR.
 */

const core = require('@actions/core');
const github = require('@actions/github');
const exec = require('@actions/exec');
const fs = require('fs').promises;
const _path = require('path');

/**
 * Main action entry point
 */
async function run() {
  try {
    // Get inputs
    const apiKey = core.getInput('api-key', { required: true });
    const orgId = core.getInput('org-id', { required: true });
    const repoPath = core.getInput('repo-path') || '.';
    const applyFixes = core.getInput('apply-fixes') === 'true';
    const failOnBlockers = core.getInput('fail-on-blockers') === 'true';
    const minScore = parseInt(core.getInput('min-score') || '70', 10);
    const createPr = core.getInput('create-pr') === 'true';
    const prBranch = core.getInput('pr-branch') || 'repograph-autofixes';
    const githubToken = core.getInput('github-token');
    const detectors = core.getInput('detectors');
    const format = core.getInput('format') || 'both';

    core.info('RepoGraph Scorecard Action Starting');
    core.info(`Repository: ${repoPath}`);
    core.info(`Organization: ${orgId}`);
    core.info(`Apply Fixes: ${applyFixes}`);
    core.info(`Create PR: ${createPr}`);

    // Install RepoGraph CLI (in production, this would be pre-installed in action image)
    core.startGroup('Installing RepoGraph CLI');
    await exec.exec('pip', ['install', '--quiet', 'repograph-cli']);
    core.endGroup();

    // Set up environment
    process.env.REPOGRAPH_API_KEY = apiKey;
    process.env.REPOGRAPH_ORG_ID = orgId;

    // Run scorecard
    core.startGroup('Running AI-Readiness Scorecard');
    const reportFile = 'scorecard-report';
    const cliArgs = [
      'ai-ready',
      '--repo', repoPath,
      '--org', orgId,
      '--format', format,
      '--output', reportFile,
    ];

    if (detectors) {
      cliArgs.push('--detectors', detectors);
    }

    let exitCode = 0;
    try {
      await exec.exec('repograph', cliArgs);
    } catch (error) {
      // Scorecard may exit with non-zero if there are violations
      exitCode = error.code || 1;
      core.warning(`Scorecard exited with code ${exitCode}`);
    }
    core.endGroup();

    // Read and parse results
    let scorecard;
    try {
      const jsonContent = await fs.readFile(`${reportFile}.json`, 'utf8');
      scorecard = JSON.parse(jsonContent);
    } catch (error) {
      core.setFailed(`Failed to read scorecard results: ${error.message}`);
      return;
    }

    // Extract metrics
    const score = scorecard.score || 0;
    const blockers = scorecard.report?.blocker_count || 0;
    const warnings = scorecard.report?.warning_count || 0;
    const info = scorecard.report?.info_count || 0;

    core.info(`Score: ${score}/100`);
    core.info(`Blockers: ${blockers}`);
    core.info(`Warnings: ${warnings}`);
    core.info(`Info: ${info}`);

    // Set outputs
    core.setOutput('score', score.toString());
    core.setOutput('blockers', blockers.toString());
    core.setOutput('warnings', warnings.toString());
    core.setOutput('info', info.toString());
    core.setOutput('report-path', `${reportFile}.md`);

    // Apply fixes if requested
    let fixesApplied = false;
    if (applyFixes) {
      core.startGroup('Applying Autofixes');
      try {
        const autofixArgs = ['autofix', 'apply', '--repo', repoPath];
        await exec.exec('repograph', autofixArgs);
        fixesApplied = true;
        core.info('Autofixes applied successfully');
      } catch (error) {
        core.warning(`Failed to apply autofixes: ${error.message}`);
      }
      core.endGroup();
    }

    // Create PR if requested and fixes were applied
    if (createPr && fixesApplied) {
      core.startGroup('Creating Pull Request');
      try {
        // Create branch and commit changes
        await exec.exec('git', ['checkout', '-b', prBranch]);
        await exec.exec('git', ['add', '-A']);
        await exec.exec('git', ['commit', '-m', 'fix: Apply RepoGraph autofixes']);
        await exec.exec('git', ['push', 'origin', prBranch]);

        // Create PR using GitHub API
        const octokit = github.getOctokit(githubToken);
        const { context } = github;

        const pr = await octokit.rest.pulls.create({
          owner: context.repo.owner,
          repo: context.repo.repo,
          title: 'RepoGraph Autofixes',
          head: prBranch,
          base: context.ref.replace('refs/heads/', ''),
          body: `## RepoGraph Autofixes\n\nThis PR contains automatic fixes from RepoGraph AI-readiness scorecard.\n\n**Score:** ${score}/100\n**Violations Fixed:** ${blockers + warnings}\n\nGenerated by [RepoGraph](https://github.com/repograph)`,
        });

        core.info(`Created PR #${pr.data.number}: ${pr.data.html_url}`);
      } catch (error) {
        core.warning(`Failed to create PR: ${error.message}`);
      }
      core.endGroup();
    }

    // Post comment to PR if in PR context
    if (github.context.payload.pull_request && githubToken) {
      core.startGroup('Posting PR Comment');
      try {
        const mdContent = await fs.readFile(`${reportFile}.md`, 'utf8');
        const octokit = github.getOctokit(githubToken);
        const { context } = github;

        await octokit.rest.issues.createComment({
          owner: context.repo.owner,
          repo: context.repo.repo,
          issue_number: context.payload.pull_request.number,
          body: `## RepoGraph AI-Readiness Scorecard\n\n${mdContent}\n\n---\n*Generated by [RepoGraph Scorecard](https://github.com/repograph)*`,
        });

        core.info('Posted scorecard results to PR comment');
      } catch (error) {
        core.warning(`Failed to post PR comment: ${error.message}`);
      }
      core.endGroup();
    }

    // Determine if action should fail
    if (failOnBlockers && blockers > 0) {
      core.setFailed(`Found ${blockers} blocker violation(s)`);
    } else if (score < minScore) {
      core.setFailed(`Score ${score} is below minimum ${minScore}`);
    } else {
      core.info('✓ Scorecard check passed');
    }

  } catch (error) {
    core.setFailed(error.message);
  }
}

run();
