"""
Invariant Rules Engine

Defines and enforces agent-friendly invariants for codebases.
Each invariant represents a best practice that makes repositories more accessible to AI agents.

Sprint 1 Task S1-T11 - Agent-Enablement Parity
"""

import ast
import re
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Dict, List, Optional, Callable, Any
import json
import logging

logger = logging.getLogger(__name__)


class InvariantSeverity(Enum):
    """Severity levels for invariant violations"""
    BLOCKER = "blocker"  # Must fix before agent onboarding
    WARNING = "warn"     # Should fix for optimal experience
    INFO = "info"        # Nice to have


@dataclass
class InvariantViolation:
    """Represents a single violation of an invariant"""
    invariant_id: str
    file_path: str
    line_number: Optional[int] = None
    column: Optional[int] = None
    message: str = ""
    severity: InvariantSeverity = InvariantSeverity.WARNING
    suggested_fix: Optional[str] = None
    context: Dict[str, Any] = field(default_factory=dict)


@dataclass
class InvariantRule:
    """Definition of an agent-friendly invariant"""
    id: str
    name: str
    description: str
    severity: InvariantSeverity
    detector: Callable
    can_autofix: bool
    context_export: Callable
    category: str
    rationale: str
    examples: List[str] = field(default_factory=list)


class InvariantRulesEngine:
    """
    Engine for detecting and enforcing agent-friendly invariants.

    Implements 9 core invariants:
    1. data-ui-selectors: Interactive elements have data-ui attributes
    2. generated-file-protection: Generated files are marked and protected
    3. relative-links: Documentation uses relative links
    4. i18n-coverage: UI strings externalized for translation
    5. folder-docs: Every directory has FOLDER.md
    6. index-files: Barrel exports (index.ts) maintained
    7. config-driven-routes: Routes defined in config files
    8. onboarding-prompts: Agent.md manifests present
    9. discovery-hooks: RepoGraph integration configured
    """

    def __init__(self):
        self.rules: Dict[str, InvariantRule] = {}
        self._register_invariants()

    def _register_invariants(self):
        """Register all core invariants"""

        # 1. Data-UI Selectors
        self.rules["data-ui-selectors"] = InvariantRule(
            id="data-ui-selectors",
            name="Data-UI Selector Coverage",
            description="All interactive elements must have data-ui attributes for reliable testing",
            severity=InvariantSeverity.BLOCKER,
            detector=self._detect_missing_data_ui,
            can_autofix=True,
            context_export=self._export_ui_elements,
            category="testing",
            rationale="AI agents need stable selectors to write reliable tests",
            examples=[
                '<button data-ui="submit-button">Submit</button>',
                '<input data-ui="email-input" type="email" />',
            ]
        )

        # 2. Generated File Protection
        self.rules["generated-file-protection"] = InvariantRule(
            id="generated-file-protection",
            name="Generated File Protection",
            description="Generated files must be marked with @generated header",
            severity=InvariantSeverity.BLOCKER,
            detector=self._detect_unprotected_generated_files,
            can_autofix=True,
            context_export=self._export_generated_files,
            category="safety",
            rationale="Prevents agents from editing auto-generated code",
            examples=[
                '// @generated - DO NOT EDIT MANUALLY',
                '# @generated by tool XYZ',
            ]
        )

        # 3. Relative Links
        self.rules["relative-links"] = InvariantRule(
            id="relative-links",
            name="Relative Documentation Links",
            description="Documentation must use relative links, not absolute URLs",
            severity=InvariantSeverity.WARNING,
            detector=self._detect_absolute_links,
            can_autofix=True,
            context_export=self._export_doc_structure,
            category="documentation",
            rationale="Relative links work across forks and local development",
            examples=[
                '[API Docs](./api/README.md)',
                '[Architecture](../docs/ARCHITECTURE.md)',
            ]
        )

        # 4. i18n Coverage
        self.rules["i18n-coverage"] = InvariantRule(
            id="i18n-coverage",
            name="i18n String Externalization",
            description="UI strings should be externalized for translation",
            severity=InvariantSeverity.WARNING,
            detector=self._detect_hardcoded_strings,
            can_autofix=True,
            context_export=self._export_i18n_keys,
            category="internationalization",
            rationale="Makes applications accessible to global users",
            examples=[
                't("common.submit")',
                'i18n.t("errors.validation")',
            ]
        )

        # 5. FOLDER Docs
        self.rules["folder-docs"] = InvariantRule(
            id="folder-docs",
            name="FOLDER.md Documentation",
            description="Every directory should have a FOLDER.md explaining its purpose",
            severity=InvariantSeverity.WARNING,
            detector=self._detect_missing_folder_docs,
            can_autofix=True,
            context_export=self._export_directory_structure,
            category="documentation",
            rationale="Helps agents understand directory organization",
            examples=[
                'src/components/FOLDER.md',
                'backend/api/FOLDER.md',
            ]
        )

        # 6. Index Files
        self.rules["index-files"] = InvariantRule(
            id="index-files",
            name="Barrel Export Indices",
            description="Directories should have index files for clean imports",
            severity=InvariantSeverity.INFO,
            detector=self._detect_missing_index_files,
            can_autofix=True,
            context_export=self._export_module_structure,
            category="architecture",
            rationale="Simplifies imports and exposes public API",
            examples=[
                'src/utils/index.ts',
                'backend/models/__init__.py',
            ]
        )

        # 7. Config-Driven Routes
        self.rules["config-driven-routes"] = InvariantRule(
            id="config-driven-routes",
            name="Configuration-Driven Routing",
            description="Routes should be defined in config files, not scattered",
            severity=InvariantSeverity.BLOCKER,
            detector=self._detect_hardcoded_routes,
            can_autofix=False,
            context_export=self._export_route_config,
            category="architecture",
            rationale="Centralized routes are easier for agents to discover and modify",
            examples=[
                'menu.config.ts',
                'routes.config.json',
            ]
        )

        # 8. Onboarding Prompts
        self.rules["onboarding-prompts"] = InvariantRule(
            id="onboarding-prompts",
            name="Agent.md Onboarding Manifest",
            description="Repository should have Agent.md manifest at root",
            severity=InvariantSeverity.WARNING,
            detector=self._detect_missing_agent_manifest,
            can_autofix=True,
            context_export=self._export_onboarding_context,
            category="onboarding",
            rationale="Explicit blueprint for AI agents to understand project",
            examples=[
                '/agent.md',
                '/Agent.md',
            ]
        )

        # 9. Discovery Hooks
        self.rules["discovery-hooks"] = InvariantRule(
            id="discovery-hooks",
            name="RepoGraph Integration Hooks",
            description="RepoGraph configuration should be present",
            severity=InvariantSeverity.INFO,
            detector=self._detect_missing_repograph_config,
            can_autofix=True,
            context_export=self._export_discovery_config,
            category="integration",
            rationale="Enables deep code navigation and analysis",
            examples=[
                '.repograph.json',
                'repograph.config.js',
            ]
        )

    def get_all_rules(self) -> List[InvariantRule]:
        """Get all registered invariant rules"""
        return list(self.rules.values())

    def get_rule(self, rule_id: str) -> Optional[InvariantRule]:
        """Get a specific invariant rule by ID"""
        return self.rules.get(rule_id)

    # Detector implementations

    def _detect_missing_data_ui(self, repo_path: Path) -> List[InvariantViolation]:
        """Detect interactive elements missing data-ui attributes"""
        violations = []

        # Scan React/JSX/TSX files
        for pattern in ["**/*.tsx", "**/*.jsx"]:
            for file_path in repo_path.glob(pattern):
                if self._is_excluded_path(file_path):
                    continue

                try:
                    content = file_path.read_text()
                    lines = content.split('\n')

                    # Detect interactive elements without data-ui
                    for i, line in enumerate(lines, 1):
                        # Check for buttons, inputs, links without data-ui
                        if re.search(r'<(button|input|a|select|textarea)\b(?![^>]*data-ui)', line):
                            violations.append(InvariantViolation(
                                invariant_id="data-ui-selectors",
                                file_path=str(file_path.relative_to(repo_path)),
                                line_number=i,
                                message=f"Interactive element missing data-ui attribute",
                                severity=InvariantSeverity.BLOCKER,
                                suggested_fix="Add data-ui attribute to element"
                            ))
                except Exception as e:
                    logger.warning(f"Error scanning {file_path}: {e}")

        return violations

    def _detect_unprotected_generated_files(self, repo_path: Path) -> List[InvariantViolation]:
        """Detect generated files without @generated marker"""
        violations = []

        # Common patterns for generated files
        generated_patterns = [
            "**/generated/**/*",
            "**/*.generated.*",
            "**/dist/**/*",
            "**/build/**/*",
        ]

        for pattern in generated_patterns:
            for file_path in repo_path.glob(pattern):
                if file_path.is_dir() or self._is_excluded_path(file_path):
                    continue

                try:
                    content = file_path.read_text()

                    # Check for @generated marker in first 10 lines
                    first_lines = '\n'.join(content.split('\n')[:10])
                    if '@generated' not in first_lines.lower():
                        violations.append(InvariantViolation(
                            invariant_id="generated-file-protection",
                            file_path=str(file_path.relative_to(repo_path)),
                            line_number=1,
                            message="Generated file missing @generated marker",
                            severity=InvariantSeverity.BLOCKER,
                            suggested_fix="Add @generated comment to file header"
                        ))
                except Exception as e:
                    logger.warning(f"Error scanning {file_path}: {e}")

        return violations

    def _detect_absolute_links(self, repo_path: Path) -> List[InvariantViolation]:
        """Detect absolute links in markdown documentation"""
        violations = []

        for file_path in repo_path.glob("**/*.md"):
            if self._is_excluded_path(file_path):
                continue

            try:
                content = file_path.read_text()
                lines = content.split('\n')

                for i, line in enumerate(lines, 1):
                    # Detect markdown links with absolute URLs to same repo
                    matches = re.finditer(r'\[([^\]]+)\]\((https?://[^\)]+)\)', line)
                    for match in matches:
                        url = match.group(2)
                        # Check if it's internal link
                        if 'github.com' in url or 'localhost' in url:
                            violations.append(InvariantViolation(
                                invariant_id="relative-links",
                                file_path=str(file_path.relative_to(repo_path)),
                                line_number=i,
                                message=f"Absolute link should be relative: {url}",
                                severity=InvariantSeverity.WARNING,
                                suggested_fix="Convert to relative path"
                            ))
            except Exception as e:
                logger.warning(f"Error scanning {file_path}: {e}")

        return violations

    def _detect_hardcoded_strings(self, repo_path: Path) -> List[InvariantViolation]:
        """Detect hardcoded UI strings that should be externalized"""
        violations = []

        for pattern in ["**/*.tsx", "**/*.jsx"]:
            for file_path in repo_path.glob(pattern):
                if self._is_excluded_path(file_path):
                    continue

                try:
                    content = file_path.read_text()
                    lines = content.split('\n')

                    for i, line in enumerate(lines, 1):
                        # Detect JSX text content that looks like user-facing strings
                        # This is a simplified heuristic
                        if re.search(r'>([A-Z][a-z\s]{10,})<', line):
                            if not re.search(r'\bt\(|i18n\.t\(', line):
                                violations.append(InvariantViolation(
                                    invariant_id="i18n-coverage",
                                    file_path=str(file_path.relative_to(repo_path)),
                                    line_number=i,
                                    message="Hardcoded string should be externalized",
                                    severity=InvariantSeverity.WARNING,
                                    suggested_fix="Use i18n translation function"
                                ))
                except Exception as e:
                    logger.warning(f"Error scanning {file_path}: {e}")

        return violations

    def _detect_missing_folder_docs(self, repo_path: Path) -> List[InvariantViolation]:
        """Detect directories without FOLDER.md"""
        violations = []

        # Get all directories with code files
        code_dirs = set()
        for pattern in ["**/*.py", "**/*.ts", "**/*.tsx", "**/*.js", "**/*.jsx"]:
            for file_path in repo_path.glob(pattern):
                if not self._is_excluded_path(file_path):
                    code_dirs.add(file_path.parent)

        # Check for FOLDER.md
        for dir_path in code_dirs:
            folder_md = dir_path / "FOLDER.md"
            if not folder_md.exists():
                violations.append(InvariantViolation(
                    invariant_id="folder-docs",
                    file_path=str(dir_path.relative_to(repo_path)),
                    message=f"Directory missing FOLDER.md documentation",
                    severity=InvariantSeverity.WARNING,
                    suggested_fix="Create FOLDER.md explaining directory purpose"
                ))

        return violations

    def _detect_missing_index_files(self, repo_path: Path) -> List[InvariantViolation]:
        """Detect directories without index files"""
        violations = []

        # Get all directories with multiple modules
        for lang_pattern, index_name in [("**/*.py", "__init__.py"), ("**/*.ts", "index.ts")]:
            module_dirs = {}
            for file_path in repo_path.glob(lang_pattern):
                if not self._is_excluded_path(file_path) and file_path.name != index_name:
                    module_dirs.setdefault(file_path.parent, []).append(file_path)

            for dir_path, files in module_dirs.items():
                if len(files) > 2:  # Only check dirs with multiple modules
                    index_file = dir_path / index_name
                    if not index_file.exists():
                        violations.append(InvariantViolation(
                            invariant_id="index-files",
                            file_path=str(dir_path.relative_to(repo_path)),
                            message=f"Directory missing {index_name} barrel export",
                            severity=InvariantSeverity.INFO,
                            suggested_fix=f"Create {index_name} with exports"
                        ))

        return violations

    def _detect_hardcoded_routes(self, repo_path: Path) -> List[InvariantViolation]:
        """Detect routes defined outside configuration files"""
        violations = []

        # Check for route config files
        route_configs = list(repo_path.glob("**/routes.config.*")) + \
                       list(repo_path.glob("**/menu.config.*"))

        if not route_configs:
            violations.append(InvariantViolation(
                invariant_id="config-driven-routes",
                file_path=".",
                message="No route configuration file found (routes.config.* or menu.config.*)",
                severity=InvariantSeverity.BLOCKER,
                suggested_fix="Create routes.config.ts with centralized route definitions"
            ))

        return violations

    def _detect_missing_agent_manifest(self, repo_path: Path) -> List[InvariantViolation]:
        """Detect missing Agent.md manifest"""
        violations = []

        agent_files = ["agent.md", "Agent.md", "AGENT.md"]
        has_manifest = any((repo_path / name).exists() for name in agent_files)

        if not has_manifest:
            violations.append(InvariantViolation(
                invariant_id="onboarding-prompts",
                file_path=".",
                message="Repository missing Agent.md onboarding manifest",
                severity=InvariantSeverity.WARNING,
                suggested_fix="Create agent.md with project blueprint for AI agents"
            ))

        return violations

    def _detect_missing_repograph_config(self, repo_path: Path) -> List[InvariantViolation]:
        """Detect missing RepoGraph configuration"""
        violations = []

        config_files = [".repograph.json", "repograph.config.js", ".repograph.yml"]
        has_config = any((repo_path / name).exists() for name in config_files)

        if not has_config:
            violations.append(InvariantViolation(
                invariant_id="discovery-hooks",
                file_path=".",
                message="Repository missing RepoGraph configuration",
                severity=InvariantSeverity.INFO,
                suggested_fix="Create .repograph.json for code navigation integration"
            ))

        return violations

    # Context export implementations

    def _export_ui_elements(self, repo_path: Path) -> Dict[str, Any]:
        """Export UI element inventory"""
        elements = []
        for pattern in ["**/*.tsx", "**/*.jsx"]:
            for file_path in repo_path.glob(pattern):
                if not self._is_excluded_path(file_path):
                    try:
                        content = file_path.read_text()
                        # Extract data-ui attributes
                        matches = re.finditer(r'data-ui="([^"]+)"', content)
                        for match in matches:
                            elements.append({
                                "selector": match.group(1),
                                "file": str(file_path.relative_to(repo_path))
                            })
                    except:
                        pass
        return {"ui_elements": elements, "count": len(elements)}

    def _export_generated_files(self, repo_path: Path) -> Dict[str, Any]:
        """Export list of generated files"""
        generated = []
        for pattern in ["**/generated/**/*", "**/*.generated.*"]:
            for file_path in repo_path.glob(pattern):
                if file_path.is_file():
                    generated.append(str(file_path.relative_to(repo_path)))
        return {"generated_files": generated, "count": len(generated)}

    def _export_doc_structure(self, repo_path: Path) -> Dict[str, Any]:
        """Export documentation structure"""
        docs = []
        for file_path in repo_path.glob("**/*.md"):
            if not self._is_excluded_path(file_path):
                docs.append(str(file_path.relative_to(repo_path)))
        return {"documentation_files": docs, "count": len(docs)}

    def _export_i18n_keys(self, repo_path: Path) -> Dict[str, Any]:
        """Export i18n translation keys"""
        keys = set()
        for pattern in ["**/locales/**/*.json", "**/i18n/**/*.json"]:
            for file_path in repo_path.glob(pattern):
                try:
                    data = json.loads(file_path.read_text())
                    keys.update(self._extract_json_keys(data))
                except:
                    pass
        return {"i18n_keys": sorted(keys), "count": len(keys)}

    def _export_directory_structure(self, repo_path: Path) -> Dict[str, Any]:
        """Export directory structure with docs"""
        structure = {}
        for folder_md in repo_path.glob("**/FOLDER.md"):
            rel_path = str(folder_md.parent.relative_to(repo_path))
            structure[rel_path] = folder_md.read_text()[:200]  # First 200 chars
        return {"directory_structure": structure, "count": len(structure)}

    def _export_module_structure(self, repo_path: Path) -> Dict[str, Any]:
        """Export module structure"""
        modules = {}
        for index_file in list(repo_path.glob("**/__init__.py")) + list(repo_path.glob("**/index.ts")):
            rel_path = str(index_file.parent.relative_to(repo_path))
            modules[rel_path] = {"index": index_file.name}
        return {"modules": modules, "count": len(modules)}

    def _export_route_config(self, repo_path: Path) -> Dict[str, Any]:
        """Export route configuration"""
        routes = {}
        for config_file in list(repo_path.glob("**/routes.config.*")) + \
                          list(repo_path.glob("**/menu.config.*")):
            try:
                content = config_file.read_text()
                routes[str(config_file.relative_to(repo_path))] = content[:500]
            except:
                pass
        return {"route_configs": routes, "count": len(routes)}

    def _export_onboarding_context(self, repo_path: Path) -> Dict[str, Any]:
        """Export onboarding context"""
        context = {}
        for agent_file in ["agent.md", "Agent.md", "AGENT.md"]:
            file_path = repo_path / agent_file
            if file_path.exists():
                context["manifest"] = file_path.read_text()[:1000]
                break
        return context

    def _export_discovery_config(self, repo_path: Path) -> Dict[str, Any]:
        """Export RepoGraph discovery configuration"""
        config = {}
        for config_file in [".repograph.json", "repograph.config.js"]:
            file_path = repo_path / config_file
            if file_path.exists():
                config["config_file"] = config_file
                try:
                    config["content"] = file_path.read_text()[:500]
                except:
                    pass
                break
        return config

    # Utility methods

    def _is_excluded_path(self, path: Path) -> bool:
        """Check if path should be excluded from scanning"""
        exclude_patterns = [
            "node_modules", ".git", "dist", "build", "__pycache__",
            ".pytest_cache", ".venv", "venv", "coverage"
        ]
        return any(pattern in str(path) for pattern in exclude_patterns)

    def _extract_json_keys(self, obj: Any, prefix: str = "") -> List[str]:
        """Recursively extract keys from JSON object"""
        keys = []
        if isinstance(obj, dict):
            for k, v in obj.items():
                full_key = f"{prefix}.{k}" if prefix else k
                keys.append(full_key)
                if isinstance(v, dict):
                    keys.extend(self._extract_json_keys(v, full_key))
        return keys

    def run_all_detectors(self, repo_path: Path) -> Dict[str, List[InvariantViolation]]:
        """Run all invariant detectors on a repository"""
        results = {}

        for rule_id, rule in self.rules.items():
            logger.info(f"Running detector: {rule.name}")
            try:
                violations = rule.detector(repo_path)
                results[rule_id] = violations
                logger.info(f"  Found {len(violations)} violations")
            except Exception as e:
                logger.error(f"Error running detector {rule_id}: {e}")
                results[rule_id] = []

        return results

    def export_all_context(self, repo_path: Path) -> Dict[str, Any]:
        """Export context from all invariants"""
        context = {}

        for rule_id, rule in self.rules.items():
            try:
                context[rule_id] = rule.context_export(repo_path)
            except Exception as e:
                logger.error(f"Error exporting context for {rule_id}: {e}")
                context[rule_id] = {}

        return context
