"""Programmatic repository builders for scorecard and CLI tests."""

from __future__ import annotations

from pathlib import Path


def build_good_scorecard_repo(tmp_path: Path) -> Path:
    repo_path = tmp_path / "good-scorecard-repo"
    _write(
        repo_path / "README.md",
        "# Good Repository Example\n\nThis repository follows the documented AI-readiness rules.\n\nSee ./src/api/README.md for API details.\n",
    )
    _write(repo_path / "src" / "FOLDER.md", "# src\n\nCore application source code.\n")
    _write(repo_path / "src" / "api" / "README.md", "# API\n\nDocumented HTTP handlers and schemas.\n")
    _write(repo_path / "src" / "components" / "README.md", "# Components\n\nReusable UI building blocks.\n")
    _write(repo_path / "src" / "permissions.py", "def check_permission(scope: str) -> bool:\n    return True\n")
    _write(
        repo_path / "src" / "api" / "routes.py",
        "from fastapi import APIRouter\n\nfrom src.permissions import check_permission\n\nrouter = APIRouter()\n\n\n@router.post(\"/users\")\ndef create_user() -> dict[str, str]:\n    \"\"\"Create a user and return the created identifier.\"\"\"\n    check_permission(\"repo:write\")\n    return {\"status\": \"ok\"}\n",
    )
    _write(
        repo_path / "src" / "api" / "schema.ts",
        "export interface CreateUserPayload {\n  email: string;\n  name: string;\n}\n",
    )
    _write(
        repo_path / "src" / "components" / "Button.tsx",
        "import { useTranslation } from 'react-i18next';\n\nexport function Button() {\n  const { t } = useTranslation();\n  return <button data-ui=\"primary-button\">{t('buttons.submit')}</button>;\n}\n",
    )
    return repo_path


def build_problematic_scorecard_repo(tmp_path: Path) -> Path:
    repo_path = tmp_path / "problematic-scorecard-repo"
    _write(
        repo_path / "README.md",
        "# Problematic Repository Example\n\nAbsolute link: /Users/example/docs/api.md\nWindows path: C:\\Users\\example\\code\\README.md\n",
    )
    _write(
        repo_path / "src" / "api" / "routes.py",
        "from fastapi import APIRouter, Depends\n\nrouter = APIRouter()\n\n\ndef get_current_user():\n    return {\"id\": \"user\"}\n\n\n@router.post(\"/users\")\ndef create_user(current_user=Depends(get_current_user)):\n    return {\"status\": \"ok\"}\n",
    )
    _write(
        repo_path / "src" / "api" / "schema.ts",
        "export interface BrokenPayload {\n  payload: any;\n}\n",
    )
    _write(
        repo_path / "src" / "components" / "BadButton.tsx",
        "export function BadButton() {\n  return <button>Create your account right now</button>;\n}\n",
    )
    _write(
        repo_path / "src" / "generated" / "api_client.py",
        "# @generated\n# This file is automatically generated. DO NOT EDIT.\n# line 3\n# line 4\n# line 5\n# line 6\n# line 7\n# line 8\n# line 9\n# line 10\n# line 11\n# line 12\n# line 13\n# line 14\n# line 15\n# line 16\n# line 17\n# line 18\n# line 19\n# line 20\nclass ApiClient:\n    def request(self):\n        return {'status': 'manual-edit'}\n",
    )
    return repo_path


def build_indexable_core_repo(tmp_path: Path) -> Path:
    repo_path = tmp_path / "indexable-core-repo"
    _write(
        repo_path / "README.md",
        "# Indexable Core Repo\n\nSmall repository used to prove the API core flow.\n",
    )
    _write(
        repo_path / "helper.py",
        "def helper() -> str:\n    return 'ok'\n",
    )
    _write(
        repo_path / "service.py",
        "from helper import helper\n\n\ndef run_service() -> str:\n    return helper()\n",
    )
    _write(
        repo_path / "api.py",
        "from service import run_service\n\n\ndef call_api() -> str:\n    return run_service()\n",
    )
    return repo_path


def build_medium_fixture_repo(dest: Path) -> Path:
    """Deterministic multi-language fixture for the migration parity corpus.

    Built on demand (never checked in — see CONTRIBUTING's fixture rule)
    by tests (and, until Phase 6 retired it, the golden-diff harness).
    Exercises the edge
    cases the python-retirement plan calls out: multiple languages,
    unicode filenames, nested areas, docs, configs, and a cross-file
    call chain.
    """
    repo_path = dest / "medium-fixture"
    _write(repo_path / "README.md", "# Medium Fixture\n\nParity corpus repo.\n")
    _write(
        repo_path / "docs" / "architecture.md",
        "# Architecture\n\nSee [auth](../src/auth/tokens.py) and [routes](../web/routes.ts).\n",
    )
    _write(repo_path / "config" / "settings.json", '{\n  "rate_limit": 10,\n  "locale": "fr"\n}\n')
    _write(repo_path / "config" / "app.yaml", "feature_flags:\n  new_flow: true\n")
    _write(
        repo_path / "src" / "auth" / "tokens.py",
        "def issue_token(user: str) -> str:\n    return f\"tok-{user}\"\n\n\n"
        "def revoke_token(token: str) -> bool:\n    return token.startswith(\"tok-\")\n",
    )
    _write(
        repo_path / "src" / "auth" / "session.py",
        "from src.auth.tokens import issue_token\n\n\n"
        "def open_session(user: str) -> str:\n    return issue_token(user)\n",
    )
    _write(
        repo_path / "src" / "billing" / "invoice.py",
        "def total(lines: list[int]) -> int:\n    return sum(lines)\n\n\n"
        "def unused_discount(total_cents: int) -> int:\n    return total_cents // 10\n",
    )
    _write(
        repo_path / "web" / "routes.ts",
        "import { openSession } from \"./session\";\n\n"
        "export function loginRoute(user: string): string {\n  return openSession(user);\n}\n",
    )
    _write(
        repo_path / "web" / "session.ts",
        "export function openSession(user: string): string {\n  return `sess-${user}`;\n}\n",
    )
    _write(
        repo_path / "legacy" / "Départ.php",
        "<?php\nfunction depart_handler() {\n    return legacy_helper();\n}\n"
        "function legacy_helper() {\n    return 1;\n}\n",
    )
    return repo_path


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
