//! Detector for edits to generated files (port of
//! `src/scorecard/detectors/generated_files.py`).

use std::path::Path;
use std::sync::OnceLock;

use regex::Regex;

use crate::model::{Finding, Severity};
use crate::walk::{py_suffix, read_file_safe, rglob_all, should_skip_file};

pub struct GeneratedFilesDetector;

const EXTENSIONS: [&str; 8] = [".py", ".ts", ".tsx", ".jsx", ".js", ".dart", ".go", ".java"];

/// Indicator patterns with their ORIGINAL Python pattern strings — the
/// evidence line quotes the pattern string of the first match, so the
/// literal spellings are load-bearing output.
const INDICATOR_SOURCES: [&str; 8] = [
    r"@generated",
    r"AUTO-?GENERATED",
    r"DO NOT EDIT",
    r"This file is automatically generated",
    r"Code generated by",
    r"Generated by:",
    r"autogenerated",
    r"<auto-generated",
];

struct Patterns {
    indicators: Vec<Regex>,
    name_patterns: Vec<Regex>,
}

fn patterns() -> &'static Patterns {
    static CELL: OnceLock<Patterns> = OnceLock::new();
    CELL.get_or_init(|| Patterns {
        indicators: INDICATOR_SOURCES
            .iter()
            .map(|src| Regex::new(&format!("(?i){src}")).unwrap())
            .collect(),
        name_patterns: vec![
            Regex::new(r"\.g\.dart$").unwrap(),
            Regex::new(r"\.generated\.(ts|js)$").unwrap(),
            Regex::new(r"_pb2\.py$").unwrap(),
            Regex::new(r"\.pb\.go$").unwrap(),
            Regex::new(r"migrations/versions/.*\.py$").unwrap(),
        ],
    })
}

impl super::Detector for GeneratedFilesDetector {
    fn name(&self) -> &'static str {
        "generated-files"
    }

    fn description(&self) -> &'static str {
        "Checks for manual edits to auto-generated files"
    }

    fn detect(&self, repo_path: &Path) -> Vec<Finding> {
        let patterns = patterns();
        let mut findings = Vec::new();

        for entry in rglob_all(repo_path) {
            if !entry.is_file || !EXTENSIONS.contains(&py_suffix(&entry.path).as_str()) {
                continue;
            }
            if should_skip_file(&entry.path) {
                continue;
            }

            // Name-pattern check runs against the FULL path string
            // (Python `str(file_path)` on the absolute rglob result).
            // Its result never gates the finding on its own — kept for
            // fidelity with the original control flow.
            let path_str = entry.path.to_string_lossy();
            let _is_generated_name = patterns
                .name_patterns
                .iter()
                .any(|p| p.is_match(path_str.as_ref()));

            let Some(content) = read_file_safe(&entry.path) else {
                continue;
            };
            if content.is_empty() {
                continue;
            }

            // First 20 lines joined back with '\n'.
            let header_text = content.split('\n').take(20).collect::<Vec<_>>().join("\n");

            // The finding is emitted only when a header marker matches
            // (a generated-looking NAME alone produces nothing — quirk
            // preserved). Evidence quotes the first matching pattern's
            // source string.
            let matched = patterns
                .indicators
                .iter()
                .zip(INDICATOR_SOURCES.iter())
                .find(|(regex, _)| regex.is_match(&header_text));
            if let Some((_, source)) = matched {
                let rel = entry
                    .path
                    .strip_prefix(repo_path)
                    .unwrap_or(&entry.path)
                    .to_string_lossy()
                    .to_string();
                findings.push(Finding {
                    detector: "generated-files".to_string(),
                    severity: Severity::Blocker,
                    message: "File marked as generated - manual edits will be overwritten"
                        .to_string(),
                    file_path: rel,
                    line_number: None,
                    evidence: Some(format!("File contains: {source}")),
                    suggestion: Some(
                        "Do not edit generated files. Modify the template/generator instead."
                            .to_string(),
                    ),
                });
            }
        }

        findings
    }
}

#[cfg(test)]
mod tests {
    use super::super::Detector;
    use super::*;
    use crate::testsupport::{build_good_scorecard_repo, build_problematic_scorecard_repo, tmpdir};

    // Translated from tests/scorecard/test_detectors.py::TestGeneratedFilesDetector.

    #[test]
    fn detects_generated_files() {
        let tmp = tmpdir("genfiles-bad");
        let repo = build_problematic_scorecard_repo(&tmp);
        let findings = GeneratedFilesDetector.detect(&repo);
        assert!(!findings.is_empty());
        assert!(findings.iter().any(|f| f.severity == Severity::Blocker));
        assert!(
            findings
                .iter()
                .any(|f| f.message.to_lowercase().contains("generated"))
        );
    }

    #[test]
    fn no_generated_files() {
        let tmp = tmpdir("genfiles-good");
        let repo = build_good_scorecard_repo(&tmp);
        assert!(GeneratedFilesDetector.detect(&repo).is_empty());
    }

    #[test]
    fn evidence_quotes_first_matching_pattern_source() {
        let tmp = tmpdir("genfiles-shape");
        let repo = build_problematic_scorecard_repo(&tmp);
        let findings = GeneratedFilesDetector.detect(&repo);
        assert_eq!(findings.len(), 1);
        let f = &findings[0];
        assert_eq!(f.file_path, "src/generated/api_client.py");
        // '@generated' precedes 'DO NOT EDIT' in the indicator list.
        assert_eq!(f.evidence.as_deref(), Some("File contains: @generated"));
        assert_eq!(f.line_number, None);
    }

    #[test]
    fn generated_name_without_marker_is_silent_and_marker_must_be_in_header() {
        let tmp = tmpdir("genfiles-quirks");
        let repo = tmp.join("r");
        std::fs::create_dir_all(repo.join("proto")).unwrap();
        // Name-generated (._pb2.py) but no header marker: NO finding.
        std::fs::write(repo.join("proto/thing_pb2.py"), "x = 1\n").unwrap();
        // Marker outside the first 20 lines: NO finding.
        let mut late = "# line\n".repeat(20);
        late.push_str("# DO NOT EDIT\n");
        std::fs::write(repo.join("late.py"), late).unwrap();
        // Case-insensitive marker inside header: finding.
        std::fs::write(repo.join("gen.ts"), "// auto-generated widget\n").unwrap();
        let findings = GeneratedFilesDetector.detect(&repo);
        assert_eq!(findings.len(), 1);
        assert_eq!(findings[0].file_path, "gen.ts");
        assert_eq!(
            findings[0].evidence.as_deref(),
            Some("File contains: AUTO-?GENERATED")
        );
    }
}
