//! Detector trait and registry (port of `src/scorecard/detectors/`).
//!
//! # Regex dialect audit (crate-skeleton commit, per the Phase 4 plan)
//!
//! Every pattern in the eight Python detectors, classified for the Rust
//! `regex` crate (no lookaround, no backreferences). Verdicts:
//! `safe` = compiles and matches identically in `regex` 1.x.
//!
//! | # | Detector | Pattern (Python) | Flags | Verdict |
//! |---|----------|------------------|-------|---------|
//! | 1-6 | data_ui_coverage | `<button[^>]*>`, `<input[^>]*>`, `<select[^>]*>`, `<form[^>]*>`, `<a[^>]*href=`, `<textarea[^>]*>` | IGNORECASE | safe (`(?i)`) |
//! | 7 | data_ui_coverage | `data-ui=["\'][\w-]+` | — | safe (Unicode `\w` in both) |
//! | 8 | i18n_gaps | `>\s*([A-Z][a-zA-Z\s]{10,})\s*<` | — | safe |
//! | 9-11 | i18n_gaps | `placeholder=["\']([^"\']{10,})["\']`, `title=...`, `aria-label=...` | — | safe |
//! | 12-15 | i18n_gaps (skip) | `t\(["\']`, `i18n\.`, `\$t\(`, `formatMessage` | — | safe |
//! | 16 | i18n_gaps | `[{}()\[\]]` | — | safe |
//! | 17-21 | relative_links | `/home/[\w/.-]+`, `/Users/[\w/.-]+`, `C:\\[\w\\.-]+`, `/var/[\w/.-]+`, `/tmp/[\w/.-]+` | — | safe |
//! | 22-23 | relative_links | dynamic `#.*` + `re.escape(path)`, `//.*` + `re.escape(path)` | — | safe (`regex::escape` — different escape set, identical semantics) |
//! | 24-31 | generated_files | `@generated`, `AUTO-?GENERATED`, `DO NOT EDIT`, `This file is automatically generated`, `Code generated by`, `Generated by:`, `autogenerated`, `<auto-generated` | IGNORECASE | safe (`(?i)`) |
//! | 32-36 | generated_files | `\.g\.dart$`, `\.generated\.(ts\|js)$`, `_pb2\.py$`, `\.pb\.go$`, `migrations/versions/.*\.py$` | — | safe (see `$` note) |
//! | 37 | route_coverage | `@(router\|app)\.(get\|post\|put\|delete\|patch)\(["\']([^"\']+)["\']` | — | safe |
//! | 38 | route_coverage | `@app\.route\(["\']([^"\']+)["\'].*methods=\[([^\]]+)\]` | — | safe |
//! | 39 | route_coverage | `(router\|app)\.(get\|post\|put\|delete\|patch)\(["\']([^"\']+)["\']` | — | safe |
//! | 40-43 | ability_coverage | `@router\.(post\|put\|delete\|patch)`, `Depends\(get_current_user\)`, `@require_auth`, `@login_required` | — | safe |
//! | 44-49 | ability_coverage | `can\(`, `check_permission`, `require_permission`, `@permission_required`, `has_permission`, `authorize\(` | — | safe |
//! | 50 | schema_drift | `class\s+(\w+)\(BaseModel\):` (finditer) | — | safe |
//! | 51 | schema_drift | `interface\s+(\w+)\s*\{` | — | safe |
//! | 52 | schema_drift | `class\s+\w+\(BaseModel\):` (re.match) | — | safe (`^`-anchored) |
//! | 53 | schema_drift | `class\s+(\w+)` | — | safe |
//! | 54 | schema_drift | `\S` (re.match) | — | safe (`^\S`) |
//! | 55 | schema_drift | `\s+\w+:\s+` (re.match) | — | safe (`^`-anchored) |
//! | 56 | schema_drift | `@validator\|@field_validator` | — | safe |
//! | 57 | schema_drift | `:\s*any\b` | — | safe (`\b` supported) |
//!
//! **Conclusion: zero patterns need lookaround or backreferences —
//! `fancy-regex` is not required; the plain `regex` crate covers all 57.**
//!
//! Known dialect-gap notes (none load-bearing here, recorded for the
//! corpus diff to police):
//! - Python `$` also matches before a trailing `\n`; Rust `$` (without
//!   `(?m)`) matches only at end of haystack. Patterns 32-36 anchor
//!   against path strings, which never end in `\n` — equivalent.
//! - `re.match(p)` anchors at start only; ported as `^p`.
//! - `\w`/`\s`/`\b` are Unicode in both dialects. Python's *non-regex*
//!   `str.strip()`/`str.split()` treat `\x1c-\x1f` as whitespace while
//!   Rust's `char::is_whitespace` does not — an accepted sliver of
//!   divergence for evidence trimming on pathological control-char
//!   input (never observed in the corpus).
//! - `re.escape` escapes more characters than `regex::escape`, but both
//!   produce literal-matching patterns — semantics identical.

use std::path::Path;

use crate::model::Finding;

/// A scorecard detector (port of `BaseDetector`). Detectors are pure
/// functions of the repository tree; shared walk/skip/read helpers live
/// in [`crate::walk`].
pub trait Detector {
    /// Detector name as it appears in reports and `--detectors` filters.
    fn name(&self) -> &'static str;
    /// Human-readable description (parity: carried but not rendered).
    fn description(&self) -> &'static str;
    /// Run detection over `repo_path` and return findings in the
    /// Python-identical order.
    fn detect(&self, repo_path: &Path) -> Vec<Finding>;
}

/// Registry of all detectors, in the exact `ALL_DETECTORS` order from
/// `src/scorecard/detectors/__init__.py` — report sections and the
/// detector-performance table depend on this order. Detectors are added
/// one per commit as each port lands (Phase 4 discipline).
pub fn all_detectors() -> Vec<Box<dyn Detector>> {
    vec![]
}
