use std::collections::HashSet;
use std::ffi::OsString;
use std::fs;
use std::io::Write;
use std::path::{Component, Path, PathBuf};
use std::process::{Command, Stdio};

use crate::util::uuid4;

const VENDORED_COMPONENTS: &[&str] = &[
    "node_modules",
    "vendor",
    "vendored",
    "third_party",
    "target",
    "dist",
    "build",
    ".venv",
    "venv",
    "site-packages",
    "coverage",
];

const GENERATED_NAME_PARTS: &[&str] = &[
    ".generated.",
    ".g.dart",
    "_pb2.py",
    ".pb.go",
    ".designer.cs",
];

const GENERATED_MARKERS: &[&str] = &[
    "@generated",
    "auto-generated",
    "automatically generated",
    "do not edit",
    "code generated by",
    "<auto-generated",
];

#[derive(Debug)]
pub struct TrackedSnapshot {
    source_root: PathBuf,
    materialized_root: PathBuf,
    pub tracked_file_count: usize,
    pub relevant_file_count: usize,
    pub excluded_vendored_count: usize,
    pub excluded_generated_count: usize,
    pub excluded_non_regular_count: usize,
    relative_paths: Vec<PathBuf>,
}

/// Which tracked files the snapshot leaves out as generated.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum GeneratedFiles {
    /// Leave out files whose name or contents mark them as generated, and
    /// files the repository marks `linguist-generated` in `.gitattributes`.
    Exclude,
    /// Keep every tracked file, so suppressed findings can be reviewed.
    Include,
}

impl TrackedSnapshot {
    pub fn materialize(repo_path: &Path) -> Result<Self, String> {
        Self::materialize_with(repo_path, GeneratedFiles::Exclude)
    }

    pub fn materialize_with(repo_path: &Path, generated: GeneratedFiles) -> Result<Self, String> {
        let source_root = git_root(repo_path)?;
        let output = Command::new("git")
            .arg("-C")
            .arg(&source_root)
            .args(["ls-files", "-z", "--cached"])
            .output()
            .map_err(|error| format!("could not list tracked files: {error}"))?;
        if !output.status.success() {
            return Err(format!(
                "could not list tracked files: {}",
                String::from_utf8_lossy(&output.stderr).trim()
            ));
        }

        let tracked_paths = split_nul_paths(&output.stdout)?;
        let attribute_generated = match generated {
            GeneratedFiles::Exclude => linguist_generated_paths(&source_root, &output.stdout)?,
            GeneratedFiles::Include => HashSet::new(),
        };
        let materialized_root = std::env::temp_dir().join(format!(
            "aethyme-quality-snapshot-{}-{}",
            std::process::id(),
            uuid4()
        ));
        fs::create_dir_all(&materialized_root)
            .map_err(|error| format!("could not create quality snapshot: {error}"))?;

        let mut snapshot = Self {
            source_root,
            materialized_root,
            tracked_file_count: tracked_paths.len(),
            relevant_file_count: 0,
            excluded_vendored_count: 0,
            excluded_generated_count: 0,
            excluded_non_regular_count: 0,
            relative_paths: Vec::new(),
        };

        for relative in tracked_paths {
            if !is_safe_relative_path(&relative) {
                snapshot.excluded_non_regular_count += 1;
                continue;
            }
            if is_vendored_path(&relative) {
                snapshot.excluded_vendored_count += 1;
                continue;
            }
            let source = snapshot.source_root.join(&relative);
            let Ok(metadata) = fs::symlink_metadata(&source) else {
                snapshot.excluded_non_regular_count += 1;
                continue;
            };
            if !metadata.file_type().is_file() {
                snapshot.excluded_non_regular_count += 1;
                continue;
            }
            let bytes = fs::read(&source).map_err(|error| {
                format!(
                    "could not read tracked file {}: {error}",
                    relative.display()
                )
            })?;
            if generated == GeneratedFiles::Exclude
                && (attribute_generated.contains(&relative) || is_generated(&relative, &bytes))
            {
                snapshot.excluded_generated_count += 1;
                continue;
            }
            let destination = snapshot.materialized_root.join(&relative);
            if let Some(parent) = destination.parent() {
                fs::create_dir_all(parent).map_err(|error| {
                    format!(
                        "could not create snapshot directory {}: {error}",
                        parent.display()
                    )
                })?;
            }
            fs::write(&destination, bytes).map_err(|error| {
                format!(
                    "could not materialize tracked file {}: {error}",
                    relative.display()
                )
            })?;
            snapshot.relative_paths.push(relative);
        }
        snapshot.relative_paths.sort();
        snapshot.relevant_file_count = snapshot.relative_paths.len();
        Ok(snapshot)
    }

    pub fn source_root(&self) -> &Path {
        &self.source_root
    }

    pub fn root(&self) -> &Path {
        &self.materialized_root
    }

    pub fn relative_paths(&self) -> &[PathBuf] {
        &self.relative_paths
    }
}

impl Drop for TrackedSnapshot {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.materialized_root);
    }
}

fn git_root(repo_path: &Path) -> Result<PathBuf, String> {
    let output = Command::new("git")
        .arg("-C")
        .arg(repo_path)
        .args(["rev-parse", "--show-toplevel"])
        .output()
        .map_err(|error| format!("could not inspect repository: {error}"))?;
    if !output.status.success() {
        return Err("quality inspection requires a Git working tree".to_string());
    }
    let root = String::from_utf8(output.stdout)
        .map_err(|_| "repository root is not valid UTF-8".to_string())?;
    Ok(PathBuf::from(root.trim_end_matches(['\n', '\r'])))
}

/// Tracked paths the repository marks `linguist-generated` (set or `true`)
/// in `.gitattributes`: the conventional declaration that a file is
/// produced by a tool or a run rather than written by hand.
fn linguist_generated_paths(
    root: &Path,
    nul_separated_paths: &[u8],
) -> Result<HashSet<PathBuf>, String> {
    let mut child = Command::new("git")
        .arg("-C")
        .arg(root)
        .args(["check-attr", "-z", "--stdin", "linguist-generated"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|error| format!("could not read generated-file attributes: {error}"))?;
    let mut stdin = child
        .stdin
        .take()
        .ok_or("could not read generated-file attributes: no stdin")?;
    let input = nul_separated_paths.to_vec();
    let writer = std::thread::spawn(move || stdin.write_all(&input));
    let output = child
        .wait_with_output()
        .map_err(|error| format!("could not read generated-file attributes: {error}"))?;
    writer
        .join()
        .map_err(|_| "could not read generated-file attributes: writer panicked".to_string())?
        .map_err(|error| format!("could not read generated-file attributes: {error}"))?;
    if !output.status.success() {
        return Err(format!(
            "could not read generated-file attributes: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        ));
    }
    // `-z` output is `<path> NUL <attribute> NUL <value> NUL` per path.
    let fields: Vec<&[u8]> = output.stdout.split(|byte| *byte == 0).collect();
    let mut generated = HashSet::new();
    for record in fields.chunks_exact(3) {
        if matches!(record[2], b"set" | b"true") {
            generated.insert(bytes_to_path(record[0])?);
        }
    }
    Ok(generated)
}

fn split_nul_paths(bytes: &[u8]) -> Result<Vec<PathBuf>, String> {
    bytes
        .split(|byte| *byte == 0)
        .filter(|path| !path.is_empty())
        .map(bytes_to_path)
        .collect()
}

#[cfg(unix)]
fn bytes_to_path(bytes: &[u8]) -> Result<PathBuf, String> {
    use std::os::unix::ffi::OsStringExt;
    Ok(PathBuf::from(OsString::from_vec(bytes.to_vec())))
}

#[cfg(not(unix))]
fn bytes_to_path(bytes: &[u8]) -> Result<PathBuf, String> {
    String::from_utf8(bytes.to_vec())
        .map(PathBuf::from)
        .map_err(|_| "tracked path is not valid UTF-8".to_string())
}

fn is_safe_relative_path(path: &Path) -> bool {
    !path.as_os_str().is_empty()
        && path
            .components()
            .all(|component| matches!(component, Component::Normal(_)))
}

fn is_vendored_path(path: &Path) -> bool {
    path.components().any(|component| {
        let Component::Normal(name) = component else {
            return false;
        };
        VENDORED_COMPONENTS.contains(&name.to_string_lossy().as_ref())
    })
}

fn is_generated(path: &Path, bytes: &[u8]) -> bool {
    let normalized_name = path.to_string_lossy().to_ascii_lowercase();
    if GENERATED_NAME_PARTS
        .iter()
        .any(|marker| normalized_name.contains(marker))
    {
        return true;
    }
    let prefix = &bytes[..bytes.len().min(64 * 1024)];
    let normalized = String::from_utf8_lossy(prefix).to_ascii_lowercase();
    GENERATED_MARKERS
        .iter()
        .any(|marker| normalized.contains(marker))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn git(root: &Path, args: &[&str]) {
        let status = Command::new("git")
            .arg("-C")
            .arg(root)
            .args(args)
            .status()
            .unwrap();
        assert!(status.success(), "git {args:?}");
    }

    #[test]
    fn materializes_only_tracked_relevant_regular_files() {
        let root = std::env::temp_dir().join(format!(
            "aethyme-quality-tracked-snapshot-{}",
            std::process::id()
        ));
        let _ = fs::remove_dir_all(&root);
        fs::create_dir_all(root.join("src")).unwrap();
        fs::create_dir_all(root.join("vendor/pkg")).unwrap();
        git(&root, &["init", "-q"]);
        fs::write(root.join("src/lib.rs"), "pub fn answer() -> u8 { 42 }\n").unwrap();
        fs::write(
            root.join("generated.ts"),
            "// DO NOT EDIT\nexport const x = 1;\n",
        )
        .unwrap();
        fs::write(
            root.join("vendor/pkg/code.ts"),
            "export const vendored = true;\n",
        )
        .unwrap();
        fs::write(root.join(".gitignore"), "ignored.tsx\n").unwrap();
        fs::write(root.join("ignored.tsx"), "<button>ignored</button>\n").unwrap();
        fs::write(root.join("scratch.tsx"), "<button>untracked</button>\n").unwrap();
        git(
            &root,
            &[
                "add",
                ".gitignore",
                "src/lib.rs",
                "generated.ts",
                "vendor/pkg/code.ts",
            ],
        );

        let snapshot = TrackedSnapshot::materialize(&root).unwrap();
        assert_eq!(snapshot.tracked_file_count, 4);
        assert_eq!(snapshot.relevant_file_count, 2);
        assert_eq!(snapshot.excluded_generated_count, 1);
        assert_eq!(snapshot.excluded_vendored_count, 1);
        assert_eq!(
            snapshot.relative_paths(),
            &[PathBuf::from(".gitignore"), PathBuf::from("src/lib.rs")]
        );
        assert!(snapshot.root().join("src/lib.rs").is_file());
        assert!(!snapshot.root().join("ignored.tsx").exists());
        assert!(!snapshot.root().join("scratch.tsx").exists());

        drop(snapshot);
        let _ = fs::remove_dir_all(&root);
    }

    #[test]
    fn linguist_generated_files_are_excluded_unless_included() {
        let root = std::env::temp_dir().join(format!(
            "aethyme-quality-linguist-generated-{}",
            std::process::id()
        ));
        let _ = fs::remove_dir_all(&root);
        fs::create_dir_all(root.join("results")).unwrap();
        git(&root, &["init", "-q"]);
        fs::write(root.join("notes.md"), "hand-written\n").unwrap();
        fs::write(root.join("results/run.json"), "{}\n").unwrap();
        fs::write(root.join("results/kept.json"), "{}\n").unwrap();
        fs::write(root.join("client.ts"), "// @generated\nexport {};\n").unwrap();
        fs::write(
            root.join(".gitattributes"),
            "results/** linguist-generated\nresults/kept.json -linguist-generated\n",
        )
        .unwrap();
        git(&root, &["add", "."]);

        let snapshot = TrackedSnapshot::materialize(&root).unwrap();
        assert_eq!(snapshot.excluded_generated_count, 2);
        assert_eq!(
            snapshot.relative_paths(),
            &[
                PathBuf::from(".gitattributes"),
                PathBuf::from("notes.md"),
                PathBuf::from("results/kept.json"),
            ]
        );

        let included = TrackedSnapshot::materialize_with(&root, GeneratedFiles::Include).unwrap();
        assert_eq!(included.excluded_generated_count, 0);
        for kept in ["results/run.json", "client.ts"] {
            assert!(
                included.relative_paths().contains(&PathBuf::from(kept)),
                "{kept} must be inspected with GeneratedFiles::Include"
            );
        }

        drop(snapshot);
        drop(included);
        let _ = fs::remove_dir_all(&root);
    }
}
