//! Test-only fixture builders — translation of the scorecard builders
//! in `tests/support/repo_builders.py`, byte-for-byte file contents so
//! the translated pytest cases assert against identical trees.
#![cfg(test)]

use std::fs;
use std::path::{Path, PathBuf};

pub fn tmpdir(tag: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!(
        "aq-fix-{tag}-{}-{:?}",
        std::process::id(),
        std::thread::current().id()
    ));
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(&dir).unwrap();
    dir
}

fn write(path: &Path, content: &str) {
    fs::create_dir_all(path.parent().unwrap()).unwrap();
    fs::write(path, content).unwrap();
}

/// Port of `build_good_scorecard_repo`.
pub fn build_good_scorecard_repo(tmp: &Path) -> PathBuf {
    let repo = tmp.join("good-scorecard-repo");
    write(
        &repo.join("README.md"),
        "# Good Repository Example\n\nThis repository follows the documented AI-readiness rules.\n\nSee ./src/api/README.md for API details.\n",
    );
    write(
        &repo.join("src/FOLDER.md"),
        "# src\n\nCore application source code.\n",
    );
    write(
        &repo.join("src/api/README.md"),
        "# API\n\nDocumented HTTP handlers and schemas.\n",
    );
    write(
        &repo.join("src/components/README.md"),
        "# Components\n\nReusable UI building blocks.\n",
    );
    write(
        &repo.join("src/permissions.py"),
        "def check_permission(scope: str) -> bool:\n    return True\n",
    );
    write(
        &repo.join("src/api/routes.py"),
        "from fastapi import APIRouter\n\nfrom src.permissions import check_permission\n\nrouter = APIRouter()\n\n\n@router.post(\"/users\")\ndef create_user() -> dict[str, str]:\n    \"\"\"Create a user and return the created identifier.\"\"\"\n    check_permission(\"repo:write\")\n    return {\"status\": \"ok\"}\n",
    );
    write(
        &repo.join("src/api/schema.ts"),
        "export interface CreateUserPayload {\n  email: string;\n  name: string;\n}\n",
    );
    write(
        &repo.join("src/components/Button.tsx"),
        "import { useTranslation } from 'react-i18next';\n\nexport function Button() {\n  const { t } = useTranslation();\n  return <button data-ui=\"primary-button\">{t('buttons.submit')}</button>;\n}\n",
    );
    repo
}

/// Port of `build_problematic_scorecard_repo`.
pub fn build_problematic_scorecard_repo(tmp: &Path) -> PathBuf {
    let repo = tmp.join("problematic-scorecard-repo");
    write(
        &repo.join("README.md"),
        "# Problematic Repository Example\n\nAbsolute link: /Users/example/docs/api.md\nWindows path: C:\\Users\\example\\code\\README.md\n",
    );
    write(
        &repo.join("src/api/routes.py"),
        "from fastapi import APIRouter, Depends\n\nrouter = APIRouter()\n\n\ndef get_current_user():\n    return {\"id\": \"user\"}\n\n\n@router.post(\"/users\")\ndef create_user(current_user=Depends(get_current_user)):\n    return {\"status\": \"ok\"}\n",
    );
    write(
        &repo.join("src/api/schema.ts"),
        "export interface BrokenPayload {\n  payload: any;\n}\n",
    );
    write(
        &repo.join("src/components/BadButton.tsx"),
        "export function BadButton() {\n  return <button>Create your account right now</button>;\n}\n",
    );
    write(
        &repo.join("src/generated/api_client.py"),
        "# @generated\n# This file is automatically generated. DO NOT EDIT.\n# line 3\n# line 4\n# line 5\n# line 6\n# line 7\n# line 8\n# line 9\n# line 10\n# line 11\n# line 12\n# line 13\n# line 14\n# line 15\n# line 16\n# line 17\n# line 18\n# line 19\n# line 20\nclass ApiClient:\n    def request(self):\n        return {'status': 'manual-edit'}\n",
    );
    repo
}
