"""Add indexing status fields to Repository model

Revision ID: 9292b9bdd8cf
Revises: 1caf4ba7b127
Create Date: 2025-10-04 11:31:22.753219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9292b9bdd8cf'
down_revision: Union[str, None] = '1caf4ba7b127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('git_url', sa.String(length=512), nullable=True))
    # Add status column as nullable first, then set default and make not null
    op.add_column('repositories', sa.Column('status', sa.String(length=50), nullable=True))
    op.execute("UPDATE repositories SET status = 'pending' WHERE status IS NULL")
    op.alter_column('repositories', 'status', nullable=False, server_default='pending')
    op.add_column('repositories', sa.Column('last_error', sa.Text(), nullable=True))
    op.add_column('repositories', sa.Column('last_synced_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'last_synced_at')
    op.drop_column('repositories', 'last_error')
    op.drop_column('repositories', 'status')
    op.drop_column('repositories', 'git_url')
    # ### end Alembic commands ###
