//! Programmatic fixture repositories.
//!
//! Successor to `tests/support/repo_builders.py` plus the per-suite
//! builders the pytest files defined inline. Fixtures are BUILT, never
//! checked in — CONTRIBUTING's fixture rule — so the bytes a suite
//! asserts against are visible in one place next to the assertions.
//!
//! `build_indexable_core_repo` and `build_medium_fixture_repo` from the
//! Python module are deliberately absent: their only consumer was the
//! migration parity harness (`scripts/migration/`), removed in
//! python-retirement Phase 6. Porting builders with no caller would
//! carry dead scaffolding into the Rust tree.

use std::path::{Path, PathBuf};

/// Write `content` to `path`, creating parent directories.
pub fn write(path: impl AsRef<Path>, content: &str) {
    let path = path.as_ref();
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .unwrap_or_else(|error| panic!("mkdir {}: {error}", parent.display()));
    }
    std::fs::write(path, content)
        .unwrap_or_else(|error| panic!("write {}: {error}", path.display()));
}

/// Read a UTF-8 file, panicking with the path on failure.
pub fn read(path: impl AsRef<Path>) -> String {
    let path = path.as_ref();
    std::fs::read_to_string(path)
        .unwrap_or_else(|error| panic!("read {}: {error}", path.display()))
}

/// A repository that follows the documented AI-readiness rules.
pub fn build_good_scorecard_repo(tmp: &Path) -> PathBuf {
    let repo = tmp.join("good-scorecard-repo");
    write(
        repo.join("README.md"),
        "# Good Repository Example\n\nThis repository follows the documented AI-readiness rules.\n\nSee ./src/api/README.md for API details.\n",
    );
    write(repo.join("src/FOLDER.md"), "# src\n\nCore application source code.\n");
    write(
        repo.join("src/api/README.md"),
        "# API\n\nDocumented HTTP handlers and schemas.\n",
    );
    write(
        repo.join("src/components/README.md"),
        "# Components\n\nReusable UI building blocks.\n",
    );
    write(
        repo.join("src/permissions.py"),
        "def check_permission(scope: str) -> bool:\n    return True\n",
    );
    write(
        repo.join("src/api/routes.py"),
        "from fastapi import APIRouter\n\nfrom src.permissions import check_permission\n\nrouter = APIRouter()\n\n\n@router.post(\"/users\")\ndef create_user() -> dict[str, str]:\n    \"\"\"Create a user and return the created identifier.\"\"\"\n    check_permission(\"repo:write\")\n    return {\"status\": \"ok\"}\n",
    );
    write(
        repo.join("src/api/schema.ts"),
        "export interface CreateUserPayload {\n  email: string;\n  name: string;\n}\n",
    );
    write(
        repo.join("src/components/Button.tsx"),
        "import { useTranslation } from 'react-i18next';\n\nexport function Button() {\n  const { t } = useTranslation();\n  return <button data-ui=\"primary-button\">{t('buttons.submit')}</button>;\n}\n",
    );
    repo
}

/// A repository that trips a blocker plus the warning detectors.
pub fn build_problematic_scorecard_repo(tmp: &Path) -> PathBuf {
    let repo = tmp.join("problematic-scorecard-repo");
    write(
        repo.join("README.md"),
        "# Problematic Repository Example\n\nAbsolute link: /Users/example/docs/api.md\nWindows path: C:\\Users\\example\\code\\README.md\n",
    );
    write(
        repo.join("src/api/routes.py"),
        "from fastapi import APIRouter, Depends\n\nrouter = APIRouter()\n\n\ndef get_current_user():\n    return {\"id\": \"user\"}\n\n\n@router.post(\"/users\")\ndef create_user(current_user=Depends(get_current_user)):\n    return {\"status\": \"ok\"}\n",
    );
    write(
        repo.join("src/api/schema.ts"),
        "export interface BrokenPayload {\n  payload: any;\n}\n",
    );
    write(
        repo.join("src/components/BadButton.tsx"),
        "export function BadButton() {\n  return <button>Create your account right now</button>;\n}\n",
    );
    write(
        repo.join("src/generated/api_client.py"),
        "# @generated\n# This file is automatically generated. DO NOT EDIT.\n# line 3\n# line 4\n# line 5\n# line 6\n# line 7\n# line 8\n# line 9\n# line 10\n# line 11\n# line 12\n# line 13\n# line 14\n# line 15\n# line 16\n# line 17\n# line 18\n# line 19\n# line 20\nclass ApiClient:\n    def request(self):\n        return {'status': 'manual-edit'}\n",
    );
    repo
}

/// The pnpm/TypeScript demo repo the enhance and skills suites deploy
/// into (the pytest `_build_repo` helper, shared by four files).
pub fn build_pnpm_demo_repo(root: &Path) -> PathBuf {
    write(
        root.join("package.json"),
        "{\"name\":\"demo\",\"scripts\":{\"test\":\"vitest\",\"dev\":\"vite\",\"build\":\"vite build\"}}\n",
    );
    write(root.join("pnpm-lock.yaml"), "lockfileVersion: '9.0'\n");
    write(root.join("src/main.ts"), "console.log('demo')\n");
    root.to_path_buf()
}

/// A repo with one fixable item per autofix fixer plus protected paths
/// the safety engine must refuse to patch.
pub fn build_fixable_repo(tmp: &Path) -> PathBuf {
    let repo = tmp.join("autofix-repo");
    write(repo.join("src/module.py"), "\"\"\"Module purpose.\"\"\"\n\nx = 1\n");
    write(repo.join("docs/page.md"), "[Absolute](/src/module.py)\n");
    write(
        repo.join("ui/Panel.tsx"),
        "import React from 'react';\nexport function Panel() { return <button>Save Changes</button>; }\n",
    );
    write(repo.join("package.json"), "{}\n");
    write(repo.join("Cargo.lock"), "# lock\n");
    write(repo.join("node_modules/pkg/index.js"), "module.exports = 1;\n");
    repo
}

/// A repo with nothing for autofix to do.
pub fn build_clean_repo(tmp: &Path) -> PathBuf {
    let repo = tmp.join("clean-repo");
    write(repo.join("README.md"), "# Nothing to fix here\n");
    repo
}

/// The two-module Python repo the graph/task navigation suite indexes.
/// Call [`bootstrap_repo_fragments`] afterwards to materialize the graph.
pub fn build_demo_source_repo(root: &Path) -> PathBuf {
    write(root.join("README.md"), "# Demo Repo\n\nSmall test repo.\n");
    write(
        root.join("src/main.py"),
        "from src.auth import validate_token\n\ndef main():\n    return validate_token()\n",
    );
    write(root.join("src/auth.py"), "def validate_token():\n    return True\n");
    root.to_path_buf()
}

/// Write graph fragments and materialize the redb store for `root`.
///
/// Graph queries read from the redb store and will not create it
/// themselves, so fixture repos must run the same two steps
/// `scripts/eval/setup-playground.sh` runs.
pub fn bootstrap_repo_fragments(root: &Path) {
    let fragments = std::process::Command::new(crate::bins::graph_index_bin())
        .args([
            "--repo-root",
            &root.to_string_lossy(),
            "--repo-name",
            "demo-repo",
            "--engine-version",
            "local-test",
            "--json",
        ])
        .output()
        .expect("spawn aethyme-graph-index");
    assert!(
        fragments.status.success(),
        "aethyme-graph-index failed: {}",
        String::from_utf8_lossy(&fragments.stderr)
    );

    let indexed = std::process::Command::new(crate::bins::engine_bin())
        .args(["index", "--repo", &root.to_string_lossy(), "--from-fragments"])
        .output()
        .expect("spawn aethyme-engine-cli index");
    assert!(
        indexed.status.success(),
        "engine index failed: {}",
        String::from_utf8_lossy(&indexed.stderr)
    );
}
