//! Safety engine for the autofixers (port of
//! `src/autofixers/safety.py`).
//!
//! This is the highest-stakes module in the retirement: it decides
//! which files the fixers may rewrite and which changes escalate to
//! requiring human approval. Every pattern list, every ordering of the
//! checks, and every escalation rule is preserved verbatim — including
//! the ones a redesign would question (see the notes on
//! `assess_risk` and `validate_changes`).

use std::fs::File;
use std::io::{BufReader, Read};
use std::path::Path;

use regex::Regex;

use super::pystr;

/// Risk levels for autofix operations. String values match the Python
/// `Enum` values (they reach stdout and the PR body).
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub enum RiskLevel {
    Low,
    Medium,
    High,
}

impl RiskLevel {
    pub fn as_str(self) -> &'static str {
        match self {
            RiskLevel::Low => "low",
            RiskLevel::Medium => "medium",
            RiskLevel::High => "high",
        }
    }
}

/// Statistics about a proposed content change (Python `ValidationStats`).
/// The counts are CHARACTER deltas — `size_change_bytes` is named for
/// bytes but computed with `len(str)`, so the name is preserved and the
/// arithmetic is code points.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ValidationStats {
    pub original_lines: i64,
    pub new_lines: i64,
    pub lines_added: i64,
    pub size_change_bytes: i64,
}

/// Validation output for a proposed change (Python `ValidationResult`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ValidationResult {
    pub safe: bool,
    pub warnings: Vec<String>,
    pub stats: ValidationStats,
}

pub const GENERATED_PATTERNS: [&str; 11] = [
    r"\.generated\.",
    r"\.gen\.",
    r"\.g\.",
    r"\.pb\.",
    r"\.pb2\.",
    r"_pb2\.py$",
    r"_pb2_grpc\.py$",
    r"-generated\.",
    r"\.auto\.",
    r"generated/",
    r"__generated__/",
];

pub const LOCK_FILES: [&str; 9] = [
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "Gemfile.lock",
    "Pipfile.lock",
    "poetry.lock",
    "composer.lock",
    "Cargo.lock",
    "go.sum",
];

pub const BUILD_DIRS: [&str; 16] = [
    "node_modules",
    "dist",
    "build",
    ".next",
    ".nuxt",
    "out",
    "target",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    "venv",
    ".venv",
    "env",
    ".tox",
    "coverage",
    ".coverage",
];

pub const GENERATED_HEADERS: [&str; 9] = [
    r"@generated",
    r"auto-generated",
    r"autogenerated",
    r"do not edit",
    r"do not modify",
    r"generated by",
    r"code generated",
    r"this file is generated",
    r"automatically generated",
];

pub const HIGH_RISK_PATTERNS: [&str; 18] = [
    r"\.env",
    r"\.env\.",
    r"config/production",
    r"config/prod",
    r"secrets",
    r"credentials",
    r"\.key$",
    r"\.pem$",
    r"\.p12$",
    r"\.pfx$",
    r"package\.json$",
    r"pyproject\.toml$",
    r"Cargo\.toml$",
    r"go\.mod$",
    r"pom\.xml$",
    r"build\.gradle$",
    r"Gemfile$",
    r"composer\.json$",
];

pub const MEDIUM_RISK_PATTERNS: [&str; 12] = [
    r"migrations/",
    r"schema\.sql$",
    r"database\.yml$",
    r"routes\.",
    r"router\.",
    r"\.route\.",
    r"api/",
    r"\.test\.",
    r"\.spec\.",
    r"(^|/)tests?/",
    r"(^|/)test_[^/]+$",
    r"_test\.py$",
];

fn compile_all(patterns: &[&str]) -> Vec<Regex> {
    patterns
        .iter()
        .map(|p| Regex::new(&format!("(?i){p}")).expect("static safety pattern must compile"))
        .collect()
}

/// Detect generated files that must not be modified.
pub struct GeneratedFileDetector {
    compiled_patterns: Vec<Regex>,
    compiled_headers: Vec<Regex>,
    build_dirs: Vec<&'static str>,
}

impl Default for GeneratedFileDetector {
    fn default() -> Self {
        Self::new()
    }
}

impl GeneratedFileDetector {
    pub fn new() -> Self {
        GeneratedFileDetector {
            compiled_patterns: compile_all(&GENERATED_PATTERNS),
            compiled_headers: compile_all(&GENERATED_HEADERS),
            build_dirs: BUILD_DIRS.to_vec(),
        }
    }

    /// Port of `is_generated`, check order preserved: lock-file name,
    /// build-directory component, path pattern, then — only for paths
    /// that exist as files — the first ten lines' header markers.
    pub fn is_generated(&self, file_path: &Path) -> bool {
        let file_str = pystr::as_posix(file_path);

        if LOCK_FILES.contains(&pystr::file_name(file_path).as_str()) {
            return true;
        }
        let parts = pystr::named_parts(file_path);
        if self
            .build_dirs
            .iter()
            .any(|dir| parts.iter().any(|part| part == dir))
        {
            return true;
        }
        if self
            .compiled_patterns
            .iter()
            .any(|pattern| pattern.is_match(&file_str))
        {
            return true;
        }

        if file_path.is_file() {
            // `except Exception` in the Python: an unreadable header is
            // logged and treated as "not generated".
            if let Some(header) = read_header_lines(file_path, 10)
                && self
                    .compiled_headers
                    .iter()
                    .any(|pattern| pattern.is_match(&header))
            {
                return true;
            }
        }

        false
    }

    /// Port of `get_safe_files`.
    pub fn get_safe_files<'a>(&self, files: &'a [std::path::PathBuf]) -> Vec<&'a std::path::PathBuf> {
        files
            .iter()
            .filter(|path| !self.is_generated(path))
            .collect()
    }
}

/// `"".join(handle.readline() for _ in range(10))` over a file opened
/// with `encoding="utf-8", errors="ignore"`. Line boundaries are found
/// on the raw bytes first (every terminator is ASCII, and dropped
/// invalid bytes are never `\n`/`\r`), so only the needed prefix is
/// read; the prefix is then decoded with the dropping error handler and
/// newline-translated the way text mode does.
fn read_header_lines(path: &Path, max_lines: usize) -> Option<String> {
    let file = File::open(path).ok()?;
    let mut reader = BufReader::new(file);
    let mut buf: Vec<u8> = Vec::new();
    let mut chunk = [0u8; 4096];
    let mut lines = 0usize;
    let mut scanned = 0usize;
    loop {
        // Count terminators in the bytes we already hold.
        while scanned < buf.len() && lines < max_lines {
            match buf[scanned] {
                b'\n' => {
                    scanned += 1;
                    lines += 1;
                }
                b'\r' => {
                    // `\r\n` is one terminator; a lone `\r` at the very
                    // end of the buffer may still be joined by a `\n`
                    // that has not been read yet.
                    if scanned + 1 < buf.len() {
                        scanned += if buf[scanned + 1] == b'\n' { 2 } else { 1 };
                        lines += 1;
                    } else {
                        break;
                    }
                }
                _ => scanned += 1,
            }
        }
        if lines >= max_lines {
            buf.truncate(scanned);
            break;
        }
        let read = reader.read(&mut chunk).ok()?;
        if read == 0 {
            // EOF: a trailing lone `\r` closes its line.
            break;
        }
        buf.extend_from_slice(&chunk[..read]);
    }
    Some(pystr::translate_newlines(&pystr::decode_utf8_ignore(&buf)))
}

/// Assess risk and validate autofix changes.
pub struct SafetyEngine {
    pub detector: GeneratedFileDetector,
    high_risk: Vec<Regex>,
    medium_risk: Vec<Regex>,
    important_patterns: Vec<(Regex, &'static str)>,
}

impl Default for SafetyEngine {
    fn default() -> Self {
        Self::new()
    }
}

impl SafetyEngine {
    pub fn new() -> Self {
        SafetyEngine {
            detector: GeneratedFileDetector::new(),
            high_risk: compile_all(&HIGH_RISK_PATTERNS),
            medium_risk: compile_all(&MEDIUM_RISK_PATTERNS),
            important_patterns: vec![
                (Regex::new(r"@[a-zA-Z]+\(").unwrap(), "decorators"),
                (Regex::new(r"def\s+\w+").unwrap(), "function definitions"),
                (Regex::new(r"class\s+\w+").unwrap(), "class definitions"),
                (
                    Regex::new(r"export\s+(default\s+)?(class|function|const)").unwrap(),
                    "exports",
                ),
            ],
        }
    }

    /// Port of `assess_risk`. Returns `Err` where the Python raises
    /// `ValueError` (generated file), which `PatchGenerator` turns into
    /// a dropped patch.
    ///
    /// The risk patterns are matched against the FULL path as posix,
    /// not the repo-relative one — so a repository living under a
    /// directory named e.g. `api` escalates every file to medium. That
    /// is the shipped behavior; parity first.
    pub fn assess_risk(&self, file_path: &Path, fix_type: &str) -> Result<RiskLevel, String> {
        let file_str = pystr::as_posix(file_path);

        if self.detector.is_generated(file_path) {
            return Err(format!(
                "Cannot modify generated file: {}",
                file_path.display()
            ));
        }
        if self.high_risk.iter().any(|p| p.is_match(&file_str)) {
            return Ok(RiskLevel::High);
        }
        if self.medium_risk.iter().any(|p| p.is_match(&file_str)) {
            return Ok(RiskLevel::Medium);
        }

        Ok(match fix_type {
            "docs_regen" => RiskLevel::Low,
            "link_fix" => RiskLevel::Low,
            "selector_insert" => RiskLevel::Medium,
            "i18n_scaffold" => RiskLevel::Medium,
            "format_fix" => RiskLevel::Low,
            _ => RiskLevel::Medium,
        })
    }

    /// Port of `validate_changes`.
    ///
    /// Two quirks are load-bearing and preserved: the doubling check is
    /// `len(new) > len(original) * 2`, so ANY non-empty content written
    /// over an empty original trips it (this is what makes every newly
    /// created `FOLDER.md` escalate from low to medium); and the
    /// "reduced X" warnings are informational only — they never clear
    /// `safe`.
    pub fn validate_changes(&self, original_content: &str, new_content: &str) -> ValidationResult {
        let orig_lines = pystr::splitlines(original_content, false);
        let new_lines = pystr::splitlines(new_content, false);
        let orig_len = pystr::char_len(original_content) as i64;
        let new_len = pystr::char_len(new_content) as i64;

        let mut result = ValidationResult {
            safe: true,
            warnings: Vec::new(),
            stats: ValidationStats {
                original_lines: orig_lines.len() as i64,
                new_lines: new_lines.len() as i64,
                lines_added: new_lines.len() as i64 - orig_lines.len() as i64,
                size_change_bytes: new_len - orig_len,
            },
        };

        if new_len > orig_len * 2 {
            result
                .warnings
                .push("File size doubled - review recommended".to_string());
            result.safe = false;
        }
        if new_lines.is_empty() && !orig_lines.is_empty() {
            result
                .warnings
                .push("All content removed - blocking change".to_string());
            result.safe = false;
        }

        for (pattern, name) in &self.important_patterns {
            let orig_count = pattern.find_iter(original_content).count();
            let new_count = pattern.find_iter(new_content).count();
            if orig_count > new_count {
                result
                    .warnings
                    .push(format!("Reduced {name} from {orig_count} to {new_count}"));
            }
        }

        result
    }

    pub fn should_skip_file(&self, file_path: &Path) -> bool {
        self.detector.is_generated(file_path)
    }

    pub fn get_approval_required(&self, risk_level: RiskLevel) -> bool {
        matches!(risk_level, RiskLevel::Medium | RiskLevel::High)
    }

    /// Port of `get_skipped_patterns` (the introspection surface).
    pub fn get_skipped_patterns(&self) -> Vec<(&'static str, Vec<&'static str>)> {
        vec![
            ("generated_patterns", GENERATED_PATTERNS.to_vec()),
            ("lock_files", LOCK_FILES.to_vec()),
            ("build_dirs", BUILD_DIRS.to_vec()),
            ("high_risk_patterns", HIGH_RISK_PATTERNS.to_vec()),
            ("medium_risk_patterns", MEDIUM_RISK_PATTERNS.to_vec()),
        ]
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::testsupport::tmpdir;
    use std::fs;
    use std::path::PathBuf;

    fn touch(path: &Path) {
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(path, "").unwrap();
    }

    // ── GeneratedFileDetector ────────────────────────────────────────
    // Translations of tests/autofixers/test_safety.py, plus the cases
    // the Python suite never covered (every lock file, every build dir,
    // every generated pattern, every header marker).

    #[test]
    fn detects_every_lock_file() {
        let tmp = tmpdir("safety-locks");
        let detector = GeneratedFileDetector::new();
        for name in LOCK_FILES {
            let path = tmp.join(name);
            touch(&path);
            assert!(detector.is_generated(&path), "lock file {name} not detected");
        }
        // Same stem, different name → not a lock file.
        let path = tmp.join("package-lock.jsonx");
        touch(&path);
        assert!(!detector.is_generated(&path));
    }

    #[test]
    fn detects_every_build_directory() {
        let tmp = tmpdir("safety-builddirs");
        let detector = GeneratedFileDetector::new();
        for dir in BUILD_DIRS {
            let path = tmp.join(dir).join("pkg").join("index.js");
            touch(&path);
            assert!(detector.is_generated(&path), "build dir {dir} not detected");
        }
    }

    #[test]
    fn detects_every_generated_path_pattern() {
        let tmp = tmpdir("safety-patterns");
        let detector = GeneratedFileDetector::new();
        for (pattern, sample) in [
            (r"\.generated\.", "schema.generated.ts"),
            (r"\.gen\.", "schema.gen.ts"),
            (r"\.g\.", "schema.g.dart"),
            (r"\.pb\.", "svc.pb.go"),
            (r"\.pb2\.", "svc.pb2.py"),
            (r"_pb2\.py$", "svc_pb2.py"),
            (r"_pb2_grpc\.py$", "svc_pb2_grpc.py"),
            (r"-generated\.", "api-generated.ts"),
            (r"\.auto\.", "types.auto.ts"),
        ] {
            let path = tmp.join(sample);
            touch(&path);
            assert!(detector.is_generated(&path), "{pattern} via {sample}");
        }
        // Directory-shaped patterns.
        for sample in ["generated/client.py", "__generated__/client.py"] {
            let path = tmp.join(sample);
            touch(&path);
            assert!(detector.is_generated(&path), "{sample}");
        }
        // Case-insensitivity (re.IGNORECASE on every pattern).
        let path = tmp.join("Schema.GENERATED.ts");
        touch(&path);
        assert!(detector.is_generated(&path));
    }

    #[test]
    fn detects_every_generated_header_marker() {
        let tmp = tmpdir("safety-headers");
        let detector = GeneratedFileDetector::new();
        for marker in GENERATED_HEADERS {
            let path = tmp.join("marker.ts");
            fs::write(&path, format!("// {marker}\n\ncode here")).unwrap();
            assert!(detector.is_generated(&path), "header {marker} not detected");
        }
        // Case-insensitive, and matched anywhere in the first 10 lines.
        let path = tmp.join("marker.ts");
        fs::write(&path, "1\n2\n3\n4\n5\n6\n7\n8\n9\n// DO NOT EDIT\n").unwrap();
        assert!(detector.is_generated(&path));
    }

    #[test]
    fn header_scan_stops_after_ten_lines() {
        let tmp = tmpdir("safety-header-window");
        let detector = GeneratedFileDetector::new();
        let path = tmp.join("late.ts");
        // Marker on line 11 — outside the window Python reads.
        let mut content = String::new();
        for i in 1..=10 {
            content.push_str(&format!("// line {i}\n"));
        }
        content.push_str("// @generated\n");
        fs::write(&path, &content).unwrap();
        assert!(!detector.is_generated(&path));

        // Marker on line 10 — inside the window.
        let path = tmp.join("late10.ts");
        let mut content = String::new();
        for i in 1..=9 {
            content.push_str(&format!("// line {i}\n"));
        }
        content.push_str("// @generated\n");
        fs::write(&path, &content).unwrap();
        assert!(detector.is_generated(&path));
    }

    #[test]
    fn header_scan_handles_crlf_and_invalid_bytes() {
        let tmp = tmpdir("safety-header-bytes");
        let detector = GeneratedFileDetector::new();
        let path = tmp.join("crlf.ts");
        fs::write(&path, b"// a\r\n// b\r\n// @generated\r\n").unwrap();
        assert!(detector.is_generated(&path));

        // errors="ignore" drops the invalid byte rather than failing.
        let path = tmp.join("binaryish.ts");
        let mut bytes = b"// \xff@generated\n".to_vec();
        bytes.extend_from_slice(b"more\n");
        fs::write(&path, &bytes).unwrap();
        assert!(detector.is_generated(&path));

        // A lone \r terminates a line the same way.
        let path = tmp.join("cr.ts");
        fs::write(&path, b"a\rb\rc\r// @generated\r").unwrap();
        assert!(detector.is_generated(&path));
    }

    #[test]
    fn does_not_detect_normal_files() {
        let tmp = tmpdir("safety-normal");
        let detector = GeneratedFileDetector::new();
        let path = tmp.join("component.tsx");
        fs::write(&path, "import React from 'react';").unwrap();
        assert!(!detector.is_generated(&path));
    }

    #[test]
    fn nonexistent_paths_skip_the_header_read() {
        let detector = GeneratedFileDetector::new();
        // No file on disk: name/parts/pattern checks still apply, the
        // header read does not (Python guards with `is_file()`).
        assert!(!detector.is_generated(Path::new("/nope/does/not/exist.md")));
        assert!(detector.is_generated(Path::new("/nope/poetry.lock")));
        assert!(detector.is_generated(Path::new("/nope/a.gen.ts")));
    }

    #[test]
    fn filters_safe_files() {
        let tmp = tmpdir("safety-filter");
        let detector = GeneratedFileDetector::new();
        let normal = tmp.join("normal.py");
        let generated = tmp.join("generated.gen.py");
        let lock = tmp.join("poetry.lock");
        for p in [&normal, &generated, &lock] {
            touch(p);
        }
        let files: Vec<PathBuf> = vec![normal.clone(), generated, lock];
        let safe = detector.get_safe_files(&files);
        assert_eq!(safe.len(), 1);
        assert_eq!(safe[0], &normal);
    }

    // ── SafetyEngine risk assessment ─────────────────────────────────

    #[test]
    fn assess_low_risk_docs() {
        let tmp = tmpdir("risk-docs");
        let engine = SafetyEngine::new();
        let path = tmp.join("README.md");
        touch(&path);
        assert_eq!(engine.assess_risk(&path, "docs_regen").unwrap(), RiskLevel::Low);
    }

    #[test]
    fn every_high_risk_pattern_escalates() {
        let tmp = tmpdir("risk-high");
        let engine = SafetyEngine::new();
        for sample in [
            ".env",
            ".env.production",
            "config/production/app.yml",
            "config/prod/app.yml",
            "secrets/token.txt",
            "credentials.json",
            "server.key",
            "server.pem",
            "cert.p12",
            "cert.pfx",
            "package.json",
            "pyproject.toml",
            "Cargo.toml",
            "go.mod",
            "pom.xml",
            "build.gradle",
            "Gemfile",
            "composer.json",
        ] {
            let path = tmp.join(sample);
            touch(&path);
            assert_eq!(
                engine.assess_risk(&path, "docs_regen").unwrap(),
                RiskLevel::High,
                "{sample} should be high risk even for a low-risk fix type"
            );
        }
    }

    #[test]
    fn every_medium_risk_pattern_escalates() {
        let tmp = tmpdir("risk-medium");
        let engine = SafetyEngine::new();
        for sample in [
            "migrations/0001_init.py",
            "schema.sql",
            "database.yml",
            "routes.py",
            "router.ts",
            "app.route.ts",
            "api/handler.py",
            "widget.test.ts",
            "widget.spec.ts",
            "tests/helper.py",
            "test/helper.py",
            "test_component.py",
            "component_test.py",
        ] {
            let path = tmp.join(sample);
            touch(&path);
            assert_eq!(
                engine.assess_risk(&path, "docs_regen").unwrap(),
                RiskLevel::Medium,
                "{sample} should be medium risk even for a low-risk fix type"
            );
        }
    }

    #[test]
    fn high_risk_wins_over_medium_risk() {
        let tmp = tmpdir("risk-order");
        let engine = SafetyEngine::new();
        // Matches BOTH `api/` (medium) and `package\.json$` (high);
        // the high list is consulted first.
        let path = tmp.join("api").join("package.json");
        touch(&path);
        assert_eq!(engine.assess_risk(&path, "docs_regen").unwrap(), RiskLevel::High);
    }

    #[test]
    fn fix_type_defaults_apply_when_no_pattern_matches() {
        let tmp = tmpdir("risk-fixtype");
        let engine = SafetyEngine::new();
        let path = tmp.join("widget.tsx");
        touch(&path);
        for (fix_type, expected) in [
            ("docs_regen", RiskLevel::Low),
            ("link_fix", RiskLevel::Low),
            ("format_fix", RiskLevel::Low),
            ("selector_insert", RiskLevel::Medium),
            ("i18n_scaffold", RiskLevel::Medium),
            ("any_fix", RiskLevel::Medium),
            ("", RiskLevel::Medium),
        ] {
            assert_eq!(
                engine.assess_risk(&path, fix_type).unwrap(),
                expected,
                "fix type {fix_type}"
            );
        }
    }

    #[test]
    fn rejects_generated_files() {
        let tmp = tmpdir("risk-generated");
        let engine = SafetyEngine::new();
        let path = tmp.join("schema.generated.ts");
        touch(&path);
        let err = engine.assess_risk(&path, "any_fix").unwrap_err();
        assert!(err.starts_with("Cannot modify generated file: "), "{err}");
    }

    #[test]
    fn generated_check_precedes_risk_patterns() {
        let tmp = tmpdir("risk-generated-order");
        let engine = SafetyEngine::new();
        // A lockfile that also matches a high-risk pattern must still
        // raise rather than return High.
        let path = tmp.join("Cargo.lock");
        touch(&path);
        assert!(engine.assess_risk(&path, "format_fix").is_err());
    }

    #[test]
    fn should_skip_generated_file() {
        let tmp = tmpdir("risk-skip");
        let engine = SafetyEngine::new();
        let path = tmp.join("node_modules").join("lib.js");
        touch(&path);
        assert!(engine.should_skip_file(&path));
    }

    #[test]
    fn approval_required_for_medium_and_high() {
        let engine = SafetyEngine::new();
        assert!(engine.get_approval_required(RiskLevel::High));
        assert!(engine.get_approval_required(RiskLevel::Medium));
        assert!(!engine.get_approval_required(RiskLevel::Low));
    }

    #[test]
    fn skipped_patterns_expose_every_list() {
        let engine = SafetyEngine::new();
        let patterns = engine.get_skipped_patterns();
        let names: Vec<&str> = patterns.iter().map(|(n, _)| *n).collect();
        assert_eq!(
            names,
            vec![
                "generated_patterns",
                "lock_files",
                "build_dirs",
                "high_risk_patterns",
                "medium_risk_patterns",
            ]
        );
        let lookup = |key: &str| {
            patterns
                .iter()
                .find(|(n, _)| *n == key)
                .map(|(_, v)| v.len())
                .unwrap()
        };
        // Arities match the Python lists exactly.
        assert_eq!(lookup("generated_patterns"), 11);
        assert_eq!(lookup("lock_files"), 9);
        assert_eq!(lookup("build_dirs"), 16);
        assert_eq!(lookup("high_risk_patterns"), 18);
        assert_eq!(lookup("medium_risk_patterns"), 12);
    }

    // ── SafetyEngine change validation ───────────────────────────────

    #[test]
    fn validates_safe_changes() {
        let engine = SafetyEngine::new();
        let validation =
            engine.validate_changes("line1\nline2\nline3", "line1\nline2 updated\nline3\nline4");
        assert!(validation.safe);
        assert_eq!(validation.stats.lines_added, 1);
        assert_eq!(validation.stats.original_lines, 3);
        assert_eq!(validation.stats.new_lines, 4);
        assert!(validation.warnings.is_empty());
    }

    #[test]
    fn detects_unsafe_deletion() {
        let engine = SafetyEngine::new();
        let validation = engine.validate_changes("def function():\n    pass\n", "");
        assert!(!validation.safe);
        assert_eq!(validation.warnings[0], "All content removed - blocking change");
        // The reduction warnings still accumulate after the blocker.
        assert!(
            validation
                .warnings
                .iter()
                .any(|w| w == "Reduced function definitions from 1 to 0")
        );
    }

    #[test]
    fn detects_large_size_increase() {
        let engine = SafetyEngine::new();
        let validation = engine.validate_changes("small", &"very large content".repeat(1000));
        assert!(!validation.safe);
        assert_eq!(validation.warnings[0], "File size doubled - review recommended");
    }

    #[test]
    fn any_content_over_an_empty_original_trips_the_doubling_check() {
        // This is why every newly created FOLDER.md escalates low →
        // medium in PatchGenerator: 0 * 2 == 0, so any output doubles.
        let engine = SafetyEngine::new();
        let validation = engine.validate_changes("", "x");
        assert!(!validation.safe);
        assert_eq!(validation.warnings, vec!["File size doubled - review recommended"]);
        // Exactly-double is NOT a trip (strict `>`).
        let validation = engine.validate_changes("ab", "abcd");
        assert!(validation.safe);
    }

    #[test]
    fn size_comparisons_count_characters_not_bytes() {
        let engine = SafetyEngine::new();
        // 3 chars / 9 bytes → 6 chars is exactly double in chars but
        // far less than double in bytes; must NOT trip.
        let validation = engine.validate_changes("日本語", "日本語日本語");
        assert!(validation.safe);
        assert_eq!(validation.stats.size_change_bytes, 3);
    }

    #[test]
    fn reduction_warnings_never_clear_safe() {
        let engine = SafetyEngine::new();
        let original = "@deco()\ndef a():\n    pass\nclass B:\n    pass\nexport function c() {}\n";
        let new = "def a():\n    pass\n";
        let validation = engine.validate_changes(original, new);
        assert!(validation.safe, "reductions are informational only");
        assert_eq!(
            validation.warnings,
            vec![
                "Reduced decorators from 1 to 0",
                "Reduced class definitions from 1 to 0",
                "Reduced exports from 1 to 0",
            ]
        );
    }

    #[test]
    fn line_counts_use_cpython_splitlines_boundaries() {
        let engine = SafetyEngine::new();
        // \u{2028} is a line boundary for str.splitlines but not for
        // Rust's str::lines.
        let validation = engine.validate_changes("a\u{2028}b", "a\u{2028}b\u{2028}c");
        assert_eq!(validation.stats.original_lines, 2);
        assert_eq!(validation.stats.new_lines, 3);
    }
}
