"""Add OAuth username and access token fields to User model

Revision ID: 1caf4ba7b127
Revises: e6a352d76653
Create Date: 2025-10-04 09:12:11.402522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1caf4ba7b127'
down_revision: Union[str, None] = 'e6a352d76653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_github_accounts_github_user_id', table_name='github_accounts')
    op.drop_index('ix_github_accounts_user_id', table_name='github_accounts')
    op.drop_table('github_accounts')
    op.add_column('users', sa.Column('github_username', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('github_access_token', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('gitlab_username', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('gitlab_access_token', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('bitbucket_username', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('bitbucket_access_token', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bitbucket_access_token')
    op.drop_column('users', 'bitbucket_username')
    op.drop_column('users', 'gitlab_access_token')
    op.drop_column('users', 'gitlab_username')
    op.drop_column('users', 'github_access_token')
    op.drop_column('users', 'github_username')
    op.create_table('github_accounts',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('github_user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('github_username', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('github_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('access_token_encrypted', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('refresh_token_encrypted', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('scopes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('avatar_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='github_accounts_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='github_accounts_pkey')
    )
    op.create_index('ix_github_accounts_user_id', 'github_accounts', ['user_id'], unique=False)
    op.create_index('ix_github_accounts_github_user_id', 'github_accounts', ['github_user_id'], unique=True)
    # ### end Alembic commands ###
