apiVersion: v1
kind: Service
metadata:
  name: aethyme-api
  namespace: aethyme-cloud
  labels:
    app: aethyme-api
    component: backend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: aethyme-api
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  sessionAffinity: None
