#!/usr/bin/env python
"""Dump the delegated CLI surface as deterministic markdown.

Introspects the Click command tree and prints every command with its
flags, env-var bindings, and defaults. The committed snapshot lives at
docs/architecture/cli-surface-v1.md; tests/local/test_cli_surface_freeze.py
regenerates and diffs, so any surface change fails CI until the freeze
doc is updated deliberately.

This is migration tooling (python-retirement-plan Phase 0). It retires
with the Python package in Phase 6; by then the surface is owned by
clap and the golden corpus.

Usage: .venv/bin/python scripts/migration/dump-cli-surface.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import click  # noqa: E402

from src.cli import cli  # noqa: E402

HEADER = """# CLI Surface v1 (frozen 2026-07-17)

Last Updated: 2026-07-29

The contract every python-retirement phase must hold: command names,
flags, env-var bindings, and defaults of the delegated (Python) surface.
Generated by `scripts/migration/dump-cli-surface.py`; guarded by
`tests/local/test_cli_surface_freeze.py` — regenerate and commit both
together for any *deliberate* surface change, and record the change in
`python-retirement-plan.md` (Phase 1 sanctions exactly one:
`repo engine-info` reinterpretation).

JSON output shapes are frozen by the golden corpus
(`scripts/migration/golden-diff.sh`), not this document. Exit codes:
Click's 0 (ok) / 1 (error) / 2 (usage); router adds 2 (root
unresolved, explore daemon-down) and 127 (spawn failure).

Native (non-delegated) router surface — `explore`, `broker`, `certify`,
`root` — is out of scope here; it is already Rust.

Flipped native during the retirement (removed from the Click tree, same
names/flags/output — golden-verified):
- `query symbol|deps|impact` (Phase 1, 2026-07-28; engine
  `query_cli` module). Known divergence: Click-style global options
  before the group (`aethyme --json query ...`) are no longer accepted;
  no in-repo consumer used that spelling.
- `graph node|children|parents|callers|callees|docs|configs|expand|
  overview` (Phase 1, 2026-07-28; engine `graph_cli` module). Same
  global-option divergence. The `_render_relation` /
  `_emit_completeness_signals` Click helpers remain in cli.py for the
  task group until it flips.
- `task pack|context|anchors|scope|next|expand|explain` (Phase 1,
  2026-07-28; engine `task_cli` module). Same global-option divergence.
  `context --json-output` keeps Python's compact-with-spaces dump; the
  Click renderer helpers and rendering/context_pack.py are deleted —
  their logic lives in task_cli with ported unit tests.
- `facts public-functions|function-usage`, `intents`, and `repo
  ingest|inspect|clear-cache|warm|engine-info` (Phase 1 closeout,
  2026-07-28; `facts_cli`/`repo_cli` modules). Reinterpretations:
  engine-info reports binary/store/daemon/ready (transports are gone);
  ingest reports engine snapshot + store state; clear-cache clears the
  legacy cache root. The rest of the repo group still delegates
  (Phases 2-3).
- `analyze dead-code` (Phase 1 final flip, 2026-07-28; `analyze_cli`
  module). All three formats ported; the observability
  `index_freshness`/`engine` blocks are reinterpreted store/binary-
  backed (the Python originals reported transport-era cache keys and
  CTO-corruptible git-subprocess state). Eval-facing answer content is
  byte-identical. engine.py is now a 72-line test bootstrap.
- RETIRED with PyO3 (decision #3, hard-delete 2026-07-28):
  `--engine-transport`, `AETHYME_ENGINE_TRANSPORT`, the transport
  registration API, and the `aethyme_py` in-process binding.
- `enhance deploy|verify` (Phase 2 flip, 2026-07-29; `aethyme-enhance`
  crate, templates embedded at build time). Deployed artifacts and
  stdout are byte-identical to the Python implementation, verified by
  `scripts/migration/enhance-golden.sh` against the last Python-side
  goldens. The temporary `AETHYME_ENHANCE_NATIVE` opt-in gate is gone;
  the router dispatches natively unconditionally. Unknown enhance
  subcommands and `--help` now produce the native
  `Error: unsupported enhance subcommand: ...` (exit 2) instead of
  Click group help.
- `repo deploy-skills|compile-skills|init-onboarding-overrides|
  validate-onboarding-overrides|init-agents-overrides|
  validate-agents-overrides|record-wrapper-invocation|
  experience-telemetry|experience-status|commit-message-template|
  lint-commit-message` (Phase 3 flip, 2026-07-29;
  `aethyme_enhance::repo_cli`). Stdout, written artifacts, telemetry
  ledger rows, and exit codes byte-identical to Python (parity harness
  over all 11 commands + a multi-command sequence; commit-hygiene
  additionally verified over a 200-commit corpus of this repo's git
  history in both text and JSON modes, zero diffs). The whole `repo`
  group is now native: unknown repo subcommands and `--help` produce
  `Error: unsupported repo subcommand: ...` (exit 2) instead of Click
  group help; usage errors keep Click's `Error: {message}` line but
  drop the preceding usage block (Phase 2 precedent). Sanctioned
  addition (plan Phase 3 risk item): the hidden
  `record-wrapper-invocation` logs argument-parse failures to the
  repo-local ledger as `wrapper.invocation-error` events instead of
  dying silently behind the deployed hooks' `|| true`.
"""


def _fmt_param(param: click.Parameter) -> str:
    if isinstance(param, click.Argument):
        return f"`{param.name}` (arg{', required' if param.required else ''})"
    assert isinstance(param, click.Option)
    names = "/".join(param.opts + param.secondary_opts)
    bits = []
    if param.is_flag:
        bits.append("flag")
    elif param.type is not None and param.type.name not in ("text",):
        bits.append(param.type.name)
    if param.envvar:
        bits.append(f"env {param.envvar}")
    if param.required:
        bits.append("required")
    if (
        param.default not in (None, False)
        and not param.is_flag
        and "Sentinel" not in repr(param.default)
    ):
        bits.append(f"default {param.default!r}")
    suffix = f" ({', '.join(bits)})" if bits else ""
    return f"`{names}`{suffix}"


def _walk(cmd: click.Command, path: str, lines: list[str]) -> None:
    full = path.strip()
    if not isinstance(cmd, click.Group) or full:
        params = [p for p in cmd.get_params(click.Context(cmd)) if p.name != "help"]
        rendered = "; ".join(_fmt_param(p) for p in params) or "—"
        kind = "group" if isinstance(cmd, click.Group) else "command"
        lines.append(f"| `{full or 'aethyme'}` | {kind} | {rendered} |")
    if isinstance(cmd, click.Group):
        for name in sorted(cmd.commands):
            _walk(cmd.commands[name], f"{full} {name}", lines)


def main() -> None:
    lines: list[str] = []
    root_params = [p for p in cli.get_params(click.Context(cli)) if p.name != "help"]
    lines.append("## Global options\n")
    for p in root_params:
        lines.append(f"- {_fmt_param(p)}")
    lines.append("\n## Commands\n")
    lines.append("| Command | Kind | Parameters |")
    lines.append("|---|---|---|")
    _walk(cli, "", lines)
    lines.append("\n## Environment variables (non-option)\n")
    lines.append("- `AETHYME_CACHE_DIR` — engine output cache root (default `/tmp/aethyme-cache`)")
    lines.append("- `AETHYME_ENGINE_TRANSPORT` — transport override (dies in Phase 1 with PyO3)")
    lines.append("- `AETHYME_ROOT` / `AETHYME_REPO` — router-side resolution (Rust, stays)")
    lines.append("- `AETHYME_REQUIRE_LOCAL_ENGINE` — test strictness (dev-only)")
    print(HEADER)
    print("\n".join(lines))


if __name__ == "__main__":
    main()
