#!/usr/bin/env python
"""Dump the delegated CLI surface as deterministic markdown.

Introspects the Click command tree and prints every command with its
flags, env-var bindings, and defaults. The committed snapshot lives at
docs/architecture/cli-surface-v1.md; tests/local/test_cli_surface_freeze.py
regenerates and diffs, so any surface change fails CI until the freeze
doc is updated deliberately.

This is migration tooling (python-retirement-plan Phase 0). It retires
with the Python package in Phase 6; by then the surface is owned by
clap and the golden corpus.

Usage: .venv/bin/python scripts/migration/dump-cli-surface.py
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import click  # noqa: E402

from src.cli import cli  # noqa: E402

HEADER = """# CLI Surface v1 (frozen 2026-07-17)

Last Updated: 2026-07-17

The contract every python-retirement phase must hold: command names,
flags, env-var bindings, and defaults of the delegated (Python) surface.
Generated by `scripts/migration/dump-cli-surface.py`; guarded by
`tests/local/test_cli_surface_freeze.py` — regenerate and commit both
together for any *deliberate* surface change, and record the change in
`python-retirement-plan.md` (Phase 1 sanctions exactly one:
`repo engine-info` reinterpretation).

JSON output shapes are frozen by the golden corpus
(`scripts/migration/golden-diff.sh`), not this document. Exit codes:
Click's 0 (ok) / 1 (error) / 2 (usage); router adds 2 (root
unresolved, explore daemon-down) and 127 (spawn failure).

Native (non-delegated) router surface — `explore`, `broker`, `certify`,
`root` — is out of scope here; it is already Rust.

Flipped native during the retirement (removed from the Click tree, same
names/flags/output — golden-verified):
- `query symbol|deps|impact` (Phase 1, 2026-07-28; engine
  `query_cli` module). Known divergence: Click-style global options
  before the group (`aethyme --json query ...`) are no longer accepted;
  no in-repo consumer used that spelling.
- `graph node|children|parents|callers|callees|docs|configs|expand|
  overview` (Phase 1, 2026-07-28; engine `graph_cli` module). Same
  global-option divergence. The `_render_relation` /
  `_emit_completeness_signals` Click helpers remain in cli.py for the
  task group until it flips.
"""


def _fmt_param(param: click.Parameter) -> str:
    if isinstance(param, click.Argument):
        return f"`{param.name}` (arg{', required' if param.required else ''})"
    assert isinstance(param, click.Option)
    names = "/".join(param.opts + param.secondary_opts)
    bits = []
    if param.is_flag:
        bits.append("flag")
    elif param.type is not None and param.type.name not in ("text",):
        bits.append(param.type.name)
    if param.envvar:
        bits.append(f"env {param.envvar}")
    if param.required:
        bits.append("required")
    if (
        param.default not in (None, False)
        and not param.is_flag
        and "Sentinel" not in repr(param.default)
    ):
        bits.append(f"default {param.default!r}")
    suffix = f" ({', '.join(bits)})" if bits else ""
    return f"`{names}`{suffix}"


def _walk(cmd: click.Command, path: str, lines: list[str]) -> None:
    full = path.strip()
    if not isinstance(cmd, click.Group) or full:
        params = [p for p in cmd.get_params(click.Context(cmd)) if p.name != "help"]
        rendered = "; ".join(_fmt_param(p) for p in params) or "—"
        kind = "group" if isinstance(cmd, click.Group) else "command"
        lines.append(f"| `{full or 'aethyme'}` | {kind} | {rendered} |")
    if isinstance(cmd, click.Group):
        for name in sorted(cmd.commands):
            _walk(cmd.commands[name], f"{full} {name}", lines)


def main() -> None:
    lines: list[str] = []
    root_params = [p for p in cli.get_params(click.Context(cli)) if p.name != "help"]
    lines.append("## Global options\n")
    for p in root_params:
        lines.append(f"- {_fmt_param(p)}")
    lines.append("\n## Commands\n")
    lines.append("| Command | Kind | Parameters |")
    lines.append("|---|---|---|")
    _walk(cli, "", lines)
    lines.append("\n## Environment variables (non-option)\n")
    lines.append("- `AETHYME_CACHE_DIR` — engine output cache root (default `/tmp/aethyme-cache`)")
    lines.append("- `AETHYME_ENGINE_TRANSPORT` — transport override (dies in Phase 1 with PyO3)")
    lines.append("- `AETHYME_ROOT` / `AETHYME_REPO` — router-side resolution (Rust, stays)")
    lines.append("- `AETHYME_REQUIRE_LOCAL_ENGINE` — test strictness (dev-only)")
    print(HEADER)
    print("\n".join(lines))


if __name__ == "__main__":
    main()
