"""Tests for drift sentinels and preflight checks."""

import pytest
from src.guardrails.sentinels import (
    DriftDetector,
    DriftSentinel,
    PreflightCheck,
    SentinelRule,
    RiskLevel,
)
from src.guardrails.schema_first import ExtractedSchema, SchemaType


class TestDriftDetector:
    """Tests for drift detection."""

    def test_detect_removed_entity(self):
        """Test detecting removed entities."""
        old_schemas = [
            ExtractedSchema(
                schema_type=SchemaType.PYTHON_PYDANTIC,
                file_path="models.py",
                content="",
                entities=['User', 'Product'],
            )
        ]

        new_schemas = [
            ExtractedSchema(
                schema_type=SchemaType.PYTHON_PYDANTIC,
                file_path="models.py",
                content="",
                entities=['User'],  # Product removed
            )
        ]

        detector = DriftDetector("/tmp")
        detections = detector.detect_schema_drift(old_schemas, new_schemas)

        assert len(detections) > 0
        removed = [d for d in detections if d.rule_id == 'schema_entity_removed']
        assert len(removed) == 1
        assert removed[0].old_value == 'Product'
        assert removed[0].risk_level == RiskLevel.HIGH

    def test_detect_added_entity(self):
        """Test detecting added entities."""
        old_schemas = [
            ExtractedSchema(
                schema_type=SchemaType.PYTHON_PYDANTIC,
                file_path="models.py",
                content="",
                entities=['User'],
            )
        ]

        new_schemas = [
            ExtractedSchema(
                schema_type=SchemaType.PYTHON_PYDANTIC,
                file_path="models.py",
                content="",
                entities=['User', 'Product'],  # Product added
            )
        ]

        detector = DriftDetector("/tmp")
        detections = detector.detect_schema_drift(old_schemas, new_schemas)

        added = [d for d in detections if d.rule_id == 'schema_entity_added']
        assert len(added) == 1
        assert added[0].new_value == 'Product'
        assert added[0].risk_level == RiskLevel.LOW

    def test_detect_removed_endpoint(self):
        """Test detecting removed API endpoints."""
        old_schemas = [
            ExtractedSchema(
                schema_type=SchemaType.OPENAPI,
                file_path="openapi.yaml",
                content="",
                endpoints=['/users', '/products'],
            )
        ]

        new_schemas = [
            ExtractedSchema(
                schema_type=SchemaType.OPENAPI,
                file_path="openapi.yaml",
                content="",
                endpoints=['/users'],  # /products removed
            )
        ]

        detector = DriftDetector("/tmp")
        detections = detector.detect_schema_drift(old_schemas, new_schemas)

        removed = [d for d in detections if d.rule_id == 'schema_endpoint_removed']
        assert len(removed) == 1
        assert removed[0].old_value == '/products'
        assert removed[0].risk_level == RiskLevel.CRITICAL

    def test_detect_generated_file_edit(self):
        """Test detecting edits to generated files."""
        content = """
# @generated DO NOT EDIT
# This file is automatically generated

class AutoGenerated:
    pass
"""

        detector = DriftDetector("/tmp")
        detections = detector.detect_generated_file_edits("auto.py", content)

        assert len(detections) > 0
        assert detections[0].rule_id == 'generated_file_edit'
        assert detections[0].risk_level == RiskLevel.HIGH

    def test_detect_route_not_in_schema(self):
        """Test detecting routes not in schema."""
        content = """
from fastapi import APIRouter

router = APIRouter()

@router.get("/users")
def get_users():
    pass

@router.post("/products")
def create_product():
    pass
"""

        known_routes = {'/users'}  # /products not in schema

        detector = DriftDetector("/tmp")
        detections = detector.detect_route_changes("routes.py", content, known_routes)

        assert len(detections) > 0
        not_in_schema = [d for d in detections if d.rule_id == 'route_not_in_schema']
        assert len(not_in_schema) == 1
        assert '/products' in not_in_schema[0].new_value


class TestPreflightCheck:
    """Tests for preflight checks."""

    def test_initialize_with_default_rules(self):
        """Test initialization with default rules."""
        checker = PreflightCheck("/tmp")

        assert len(checker.rules) > 0
        rule_ids = [r.rule_id for r in checker.rules]
        assert 'no_generated_edits' in rule_ids
        assert 'no_breaking_schema' in rule_ids
        assert 'no_route_drift' in rule_ids

    def test_run_checks_all_pass(self):
        """Test running checks when all pass."""
        checker = PreflightCheck("/tmp")

        context = {
            'files': [
                {'path': 'normal.py', 'content': 'def func(): pass'},
            ],
            'old_schemas': [],
            'new_schemas': [],
            'known_routes': set(),
        }

        results = checker.run_checks(context)

        assert results['passed'] is True
        assert results['blocked'] is False
        assert results['total_detections'] == 0

    def test_run_checks_with_violations(self, tmp_path):
        """Test running checks with violations."""
        checker = PreflightCheck(str(tmp_path))

        context = {
            'files': [
                {
                    'path': 'generated.py',
                    'content': '# @generated\nclass Auto: pass',
                },
            ],
            'old_schemas': [],
            'new_schemas': [],
            'known_routes': set(),
        }

        results = checker.run_checks(context)

        assert results['passed'] is False
        assert len(results['detections']) > 0

    def test_add_custom_rule(self):
        """Test adding custom sentinel rule."""
        checker = PreflightCheck("/tmp")

        def custom_check(context):
            return []

        rule = SentinelRule(
            rule_id='custom_rule',
            name='Custom Rule',
            description='Custom check',
            risk_level=RiskLevel.MEDIUM,
            check_function=custom_check,
        )

        initial_count = len(checker.rules)
        checker.add_rule(rule)

        assert len(checker.rules) == initial_count + 1

    def test_disable_rule(self):
        """Test disabling a rule."""
        checker = PreflightCheck("/tmp")

        checker.disable_rule('no_generated_edits')

        rule = next(r for r in checker.rules if r.rule_id == 'no_generated_edits')
        assert rule.enabled is False


class TestDriftSentinel:
    """Tests for drift sentinel."""

    def test_set_baseline(self, tmp_path):
        """Test setting baseline schemas."""
        # Create schema file
        schema_file = tmp_path / "models.py"
        schema_file.write_text("""
from pydantic import BaseModel

class User(BaseModel):
    id: int
""")

        sentinel = DriftSentinel(str(tmp_path))
        sentinel.set_baseline()

        assert sentinel._baseline_schemas is not None
        assert len(sentinel._baseline_schemas) > 0

    def test_check_drift_no_changes(self, tmp_path):
        """Test drift check with no changes."""
        sentinel = DriftSentinel(str(tmp_path))
        sentinel.set_baseline()

        results = sentinel.check_drift([])

        # With no baseline changes, should be minimal detections
        assert 'total_detections' in results

    def test_targeted_fetch(self):
        """Test targeted fetch for high-risk detections."""
        sentinel = DriftSentinel("/tmp")

        from src.guardrails.sentinels import DriftDetection

        detections = [
            DriftDetection(
                rule_id='test',
                risk_level=RiskLevel.CRITICAL,
                description='Critical issue',
                file_path='critical.py',
            ),
            DriftDetection(
                rule_id='test2',
                risk_level=RiskLevel.LOW,
                description='Low issue',
                file_path='low.py',
            ),
        ]

        fetch_results = sentinel.targeted_fetch(detections)

        assert 'files_to_fetch' in fetch_results
        assert 'critical.py' in fetch_results['files_to_fetch']
        # Low risk shouldn't trigger fetch
        assert 'low.py' not in fetch_results['files_to_fetch']
