use super::*;

fn git(repo: &Path, args: &[&str]) {
    assert!(
        Command::new("git")
            .args(args)
            .current_dir(repo)
            .env_remove("GIT_DIR")
            .env_remove("GIT_WORK_TREE")
            .env_remove("GIT_INDEX_FILE")
            .status()
            .unwrap()
            .success()
    );
}

fn write(repo: &Path, path: &str, content: &str) {
    let full = repo.join(path);
    std::fs::create_dir_all(full.parent().unwrap()).unwrap();
    std::fs::write(full, content).unwrap();
}

fn options() -> SourceSearchOptions {
    SourceSearchOptions {
        symbol_cache: SymbolCache::Disabled,
        ..SourceSearchOptions::default()
    }
}

fn targets(result: &SourceFallback) -> Vec<&str> {
    result
        .hints
        .iter()
        .map(|hint| hint.target.as_str())
        .collect()
}

/// A small repository with source, docs, a vendored copy, generated
/// output and tests that all mention the same behavior.
fn fixture() -> tempfile::TempDir {
    let repo = tempfile::tempdir().unwrap();
    let root = repo.path();
    git(root, &["init", "-q"]);
    write(
        root,
        "src/net/backoff.py",
        "import random\n\n\
             def compute_retry_delay(attempt, base=0.5):\n\
             \x20   \"\"\"Exponential retry delay with jitter.\"\"\"\n\
             \x20   delay = base * (2 ** attempt)\n\
             \x20   return delay + random.random()\n",
    );
    write(
        root,
        "src/net/client.py",
        "from .backoff import compute_retry_delay\n\n\
             class Client:\n\
             \x20   def send(self, request):\n\
             \x20       return self.transport.send(request)\n",
    );
    write(
        root,
        "docs/design/retry-delay.md",
        "# Retry delay design\n\nThe retry delay grows exponentially. Retry delay retry delay.\n\
             Each retry doubles the delay; the retry delay has jitter.\n",
    );
    write(
        root,
        "vendor/httplib/retry.py",
        "def compute_retry_delay(attempt):\n    # retry delay retry delay\n    return attempt\n",
    );
    write(
        root,
        "src/generated/api_pb2.py",
        "# Generated by the protocol buffer compiler.  DO NOT EDIT!\n\
             RETRY_DELAY = 1\nretry_delay_field = 2\n",
    );
    write(
        root,
        "tests/test_backoff.py",
        "from src.net.backoff import compute_retry_delay\n\n\
             def test_retry_delay_grows():\n    assert compute_retry_delay(2) > compute_retry_delay(1)\n",
    );
    write(
        root,
        "README.md",
        "# Example\n\nA client with retry delay.\n",
    );
    git(root, &["add", "--all"]);
    repo
}

#[test]
fn behavior_request_ranks_the_defining_source_first() {
    let repo = fixture();
    let result = inspect_with(repo.path(), "How is the retry delay computed?", &options());
    assert!(result.complete, "{:?}", result.incomplete_reason);
    let targets = targets(&result);
    assert_eq!(targets[0], "src/net/backoff.py", "{targets:?}");
    let first = &result.hints[0];
    let line = first.evidence["line_refs"][0]["line"].as_u64().unwrap();
    assert_eq!(line, 3, "{}", first.evidence);
}

#[test]
fn docs_vendored_generated_and_tests_rank_below_source() {
    let repo = fixture();
    let result = inspect_with(repo.path(), "retry delay", &options());
    let targets = targets(&result);
    let position = |path: &str| targets.iter().position(|target| *target == path);
    let source = position("src/net/backoff.py").expect("source present");
    for other in [
        "docs/design/retry-delay.md",
        "vendor/httplib/retry.py",
        "src/generated/api_pb2.py",
        "tests/test_backoff.py",
    ] {
        if let Some(other_position) = position(other) {
            assert!(
                source < other_position,
                "{other} outranks source: {targets:?}"
            );
        }
    }
}

#[test]
fn symbol_definition_match_ranks_its_file_first() {
    let repo = tempfile::tempdir().unwrap();
    let root = repo.path();
    git(root, &["init", "-q"]);
    write(
        root,
        "app/session.ts",
        "export class SessionStore {\n  refreshAccessToken(): void {}\n}\n",
    );
    // Mentions the words more often, but defines nothing by that name.
    write(
        root,
        "app/notes.ts",
        "// refresh the access token: refresh access token, token refresh\n\
             const refreshCount = 1; // access token refresh token access\n",
    );
    git(root, &["add", "--all"]);
    let result = inspect_with(root, "where is refreshAccessToken", &options());
    assert_eq!(
        targets(&result)[0],
        "app/session.ts",
        "{:#?}",
        result
            .hints
            .iter()
            .map(|hint| &hint.evidence)
            .collect::<Vec<_>>()
    );
    let first = &result.hints[0];
    assert_eq!(first.evidence["symbol_match"]["name"], "refreshAccessToken");
    assert_eq!(first.evidence["symbol_match"]["exact"], true);
    assert_eq!(first.evidence["line_refs"][0]["line"], 2);
}

#[test]
fn untracked_files_are_searched_but_ignored_hidden_and_symlinked_files_are_not() {
    let repo = tempfile::tempdir().unwrap();
    let root = repo.path();
    git(root, &["init", "-q"]);
    write(root, "storage.rs", "fn cleanup_cache() {}\n");
    write(root, ".gitignore", "ignored.rs\n");
    write(root, "ignored.rs", "fn cleanup_cache() {}\n");
    write(root, ".env", "cleanup cache secret\n");
    #[cfg(unix)]
    std::os::unix::fs::symlink("/etc/passwd", root.join("cleanup.rs")).unwrap();
    git(root, &["add", "storage.rs", ".gitignore"]);
    write(root, "later.rs", "fn cleanup_cache_later() {}\n");
    let result = inspect_with(root, "where is cleanup cache", &options());
    let targets = targets(&result);
    assert!(targets.contains(&"storage.rs"), "{targets:?}");
    assert!(targets.contains(&"later.rs"), "{targets:?}");
    for excluded in [".env", "ignored.rs", "cleanup.rs", ".gitignore"] {
        assert!(
            !targets.contains(&excluded),
            "{excluded} leaked: {targets:?}"
        );
    }
    for hint in &result.hints {
        assert_eq!(hint.evidence["graph_available"], false);
    }
}

#[test]
fn strong_fallback_envelope_reports_the_rule_but_stays_navigation_only() {
    let repo = fixture();
    let envelope = super::super::graph_unavailable_response(
        repo.path(),
        "retry delay",
        "task_localization_query",
        "test",
        "missing",
        "fixture".into(),
    );
    // Promotion is off (GRAPH_FREE_ANSWER_PROMOTION): the rule's verdict is
    // measured, not acted on.
    assert!(!envelope.safe_to_use_as_answer);
    assert!(envelope.safe_to_use_as_navigation);
    assert!(envelope.answer.is_empty());
    let top = &envelope.navigation_hints[0];
    assert_eq!(top.target, "src/net/backoff.py");
    assert_eq!(top.evidence["graph_available"], false);
    let policy = &envelope.trust_policy;
    assert_eq!(policy.trust_policy, "verify_before_use");
    assert_eq!(policy.evidence_level, "source_navigation");
    assert!(policy.degraded);
    assert!(
        policy.reason.contains("not caller or impact evidence"),
        "{}",
        policy.reason
    );
    assert_eq!(envelope.status, "degraded");
    assert!(!repo.path().join(".aethyme").exists());
    let observability = envelope.observability.as_ref().unwrap();
    assert_eq!(observability["readiness"]["status"], "ready");
    assert_eq!(observability["source_fallback"]["complete"], true);
    assert!(observability["source_fallback"]["reason"].is_null());
    assert_eq!(
        observability["source_fallback"]["answer_safety"]["safe"],
        true
    );
    let json = serde_json::to_value(&envelope).unwrap();
    let targets = json["subsystems"][0]["top_verification_targets"]
        .as_array()
        .unwrap();
    assert_eq!(targets[0]["path"], "src/net/backoff.py");
}

#[test]
fn incomplete_fallback_envelope_is_navigation_only() {
    let repo = fixture();
    let envelope = super::super::graph_unavailable_response_with(
        repo.path(),
        "retry delay",
        "task_localization_query",
        "test",
        "missing",
        "fixture".into(),
        &SourceSearchOptions {
            budget: Duration::ZERO,
            ..options()
        },
    );
    assert!(!envelope.safe_to_use_as_answer);
    assert!(envelope.answer.is_empty());
    assert_eq!(envelope.trust_policy.trust_policy, "verify_before_use");
    assert!(
        envelope.trust_policy.reason.contains("search_incomplete"),
        "{}",
        envelope.trust_policy.reason
    );
}

fn signal(score: f64, coverage: f64, exact_symbol: Option<&str>) -> HitSignal {
    HitSignal {
        score,
        coverage,
        exact_symbol: exact_symbol.map(str::to_string),
    }
}

#[test]
fn exact_unique_symbol_definition_is_answer_safe() {
    let signals = [
        signal(4.0, 0.6, Some("loadtoken")),
        signal(3.9, 1.0, None),
        signal(1.0, 0.5, Some("storetoken")),
    ];
    assert_eq!(
        answer_safety(&signals, true),
        AnswerSafety {
            safe: true,
            rule: "exact_symbol_definition"
        }
    );
}

#[test]
fn dominant_coverage_with_clear_margin_is_answer_safe() {
    let signals = [signal(6.0, 0.9, None), signal(3.0, 1.0, None)];
    assert_eq!(answer_safety(&signals, true).rule, "dominant_term_coverage");
    assert!(answer_safety(&signals, true).safe);
    assert!(answer_safety(&signals[..1], true).safe, "sole hit");
}

#[test]
fn ambiguous_weak_or_incomplete_evidence_is_not_answer_safe() {
    for (signals, complete, rule) in [
        (vec![], true, "no_hits"),
        (vec![], false, "search_incomplete"),
        (
            vec![signal(9.0, 1.0, Some("loadtoken"))],
            false,
            "search_incomplete",
        ),
        (
            vec![signal(9.0, 1.0, None), signal(1.0, 0.2, None)],
            false,
            "search_incomplete",
        ),
        (
            vec![
                signal(5.0, 1.0, Some("loadtoken")),
                signal(4.8, 1.0, Some("loadtoken")),
            ],
            true,
            "ambiguous_symbol_definition",
        ),
        (
            vec![signal(5.0, 1.0, None), signal(4.0, 1.0, None)],
            true,
            "no_clear_margin",
        ),
        (
            vec![signal(9.0, 0.5, None), signal(1.0, 0.5, None)],
            true,
            "low_term_coverage",
        ),
    ] {
        let verdict = answer_safety(&signals, complete);
        assert_eq!(
            verdict,
            AnswerSafety { safe: false, rule },
            "{signals:?} complete={complete}"
        );
    }
}

#[test]
fn duplicated_symbol_still_answers_on_dominant_coverage() {
    let signals = [
        signal(9.0, 1.0, Some("loadtoken")),
        signal(2.0, 0.7, Some("loadtoken")),
    ];
    assert_eq!(answer_safety(&signals, true).rule, "dominant_term_coverage");
}

#[test]
fn search_reports_its_answer_safety_verdict() {
    let repo = tempfile::tempdir().unwrap();
    let root = repo.path();
    git(root, &["init", "-q"]);
    write(
        root,
        "app/session.ts",
        "export class SessionStore {\n  refreshAccessToken(): void {}\n}\n",
    );
    write(root, "app/notes.ts", "// access token notes\n");
    git(root, &["add", "--all"]);
    let result = inspect_with(root, "where is refreshAccessToken", &options());
    assert_eq!(
        result.answer_safety,
        AnswerSafety {
            safe: true,
            rule: "exact_symbol_definition"
        }
    );
    let incomplete = inspect_with(
        root,
        "where is refreshAccessToken",
        &SourceSearchOptions {
            budget: Duration::ZERO,
            ..options()
        },
    );
    assert!(!incomplete.answer_safety.safe);
    assert_eq!(incomplete.observability()["answer_safety"]["safe"], false);
}

#[test]
fn missing_repository_has_no_claims() {
    let repo = tempfile::tempdir().unwrap();
    let result = inspect(&repo.path().join("missing"), "cleanup");
    assert!(result.hints.is_empty());
}

#[test]
fn non_git_directories_are_walked() {
    let repo = tempfile::tempdir().unwrap();
    write(
        repo.path(),
        "lib/queue.rb",
        "class JobQueue\n  def drain; end\nend\n",
    );
    write(repo.path(), ".hidden/queue.rb", "class JobQueue; end\n");
    let result = inspect_with(repo.path(), "job queue drain", &options());
    assert_eq!(result.listing, "filesystem");
    assert_eq!(targets(&result), ["lib/queue.rb"]);
}

#[test]
fn exhausted_budget_is_reported_as_incomplete() {
    let repo = fixture();
    let result = inspect_with(
        repo.path(),
        "retry delay",
        &SourceSearchOptions {
            budget: Duration::ZERO,
            ..options()
        },
    );
    assert!(!result.complete);
    assert_eq!(result.incomplete_reason, Some("time_budget_exhausted"));
    assert!(result.truncated);
    assert!(result.observability()["complete"] == false);
}

#[test]
fn hit_count_is_configurable_and_ranking_is_deterministic() {
    let repo = tempfile::tempdir().unwrap();
    let root = repo.path();
    git(root, &["init", "-q"]);
    for index in 0..40 {
        write(
            root,
            &format!("src/cache_{index:02}.rs"),
            &format!("fn cache_{index}() {{ /* cache */ }}\n"),
        );
    }
    git(root, &["add", "--all"]);
    let first = inspect_with(root, "cache", &options());
    let second = inspect_with(root, "cache", &options());
    assert!(first.complete);
    assert_eq!(first.scanned_files, 40);
    assert_eq!(first.hints.len(), DEFAULT_SOURCE_SEARCH_HITS);
    assert!(first.truncated);
    assert_eq!(targets(&first), targets(&second));
    let three = inspect_with(
        root,
        "cache",
        &SourceSearchOptions {
            max_hits: 3,
            ..options()
        },
    );
    assert_eq!(three.hints.len(), 3);
}

#[test]
fn a_focused_file_outranks_a_hub_that_mentions_everything() {
    let repo = tempfile::tempdir().unwrap();
    let root = repo.path();
    git(root, &["init", "-q"]);
    // The hub mentions the request's words more often in absolute terms,
    // spread over a file thirty times the size of the focused one.
    let mut hub = String::from("// Application entry point.\n");
    for index in 0..300 {
        hub.push_str(&format!(
            "fn handler_{index}(request: Request) -> Response {{ route(request) }}\n"
        ));
        if index % 20 == 0 {
            hub.push_str(
                "// quota reset window is configured elsewhere\nlet quota = load_quota();\n",
            );
        }
    }
    write(root, "src/main.rs", &hub);
    write(
        root,
        "src/limits.rs",
        "/// When a quota resets.\npub fn quota_reset_window(plan: &Plan) -> Duration {\n    plan.window\n}\n",
    );
    for index in 0..10 {
        write(
            root,
            &format!("src/other_{index}.rs"),
            "fn unrelated() {}\n",
        );
    }
    git(root, &["add", "--all"]);
    let result = inspect_with(
        root,
        "Where is the quota reset window computed?",
        &options(),
    );
    assert_eq!(
        targets(&result)[0],
        "src/limits.rs",
        "{:?}",
        targets(&result)
    );
    let first = &result.hints[0];
    assert_eq!(
        first.evidence["line_refs"][0]["symbol"], "quota_reset_window",
        "{}",
        first.evidence
    );
}

#[test]
fn the_span_is_the_definition_densest_in_request_terms() {
    let repo = tempfile::tempdir().unwrap();
    let root = repo.path();
    git(root, &["init", "-q"]);
    write(
        root,
        "billing/invoice.py",
        "import retry\n\n\
         def render_invoice(invoice):\n\
         \x20   return str(invoice)\n\n\
         def invoice_retry_delay(attempt):\n\
         \x20   # retry delay doubles per attempt\n\
         \x20   delay = 2 ** attempt\n\
         \x20   return delay\n",
    );
    git(root, &["add", "--all"]);
    let result = inspect_with(root, "invoice retry delay", &options());
    let refs = &result.hints[0].evidence["line_refs"];
    assert_eq!(refs[0]["line"], 6, "{refs}");
    assert_eq!(refs[0]["symbol"], "invoice_retry_delay", "{refs}");
}
