"""Safety engine for autofixers."""

from __future__ import annotations

import re
from enum import Enum
from pathlib import Path
from typing import TypedDict

from ._log import get_logger

logger = get_logger()


class ValidationStats(TypedDict):
    """Statistics about a proposed content change."""

    original_lines: int
    new_lines: int
    lines_added: int
    size_change_bytes: int


class ValidationResult(TypedDict):
    """Validation output for a proposed change."""

    safe: bool
    warnings: list[str]
    stats: ValidationStats


class RiskLevel(Enum):
    """Risk levels for autofix operations."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class GeneratedFileDetector:
    """Detect generated files that should not be modified."""

    GENERATED_PATTERNS = [
        r"\.generated\.",
        r"\.gen\.",
        r"\.g\.",
        r"\.pb\.",
        r"\.pb2\.",
        r"_pb2\.py$",
        r"_pb2_grpc\.py$",
        r"-generated\.",
        r"\.auto\.",
        r"generated/",
        r"__generated__/",
    ]
    LOCK_FILES = [
        "package-lock.json",
        "yarn.lock",
        "pnpm-lock.yaml",
        "Gemfile.lock",
        "Pipfile.lock",
        "poetry.lock",
        "composer.lock",
        "Cargo.lock",
        "go.sum",
    ]
    BUILD_DIRS = [
        "node_modules",
        "dist",
        "build",
        ".next",
        ".nuxt",
        "out",
        "target",
        "__pycache__",
        ".pytest_cache",
        ".mypy_cache",
        "venv",
        ".venv",
        "env",
        ".tox",
        "coverage",
        ".coverage",
    ]
    GENERATED_HEADERS = [
        r"@generated",
        r"auto-generated",
        r"autogenerated",
        r"do not edit",
        r"do not modify",
        r"generated by",
        r"code generated",
        r"this file is generated",
        r"automatically generated",
    ]

    def __init__(self):
        self.compiled_patterns = [re.compile(pattern, re.IGNORECASE) for pattern in self.GENERATED_PATTERNS]
        self.compiled_headers = [re.compile(pattern, re.IGNORECASE) for pattern in self.GENERATED_HEADERS]

    def is_generated(self, file_path: Path) -> bool:
        """Check if a file is generated and should be skipped."""
        file_str = file_path.as_posix()

        if file_path.name in self.LOCK_FILES:
            return True
        if any(build_dir in file_path.parts for build_dir in self.BUILD_DIRS):
            return True
        if any(pattern.search(file_str) for pattern in self.compiled_patterns):
            return True

        if file_path.is_file():
            try:
                with open(file_path, encoding="utf-8", errors="ignore") as handle:
                    header = "".join(handle.readline() for _ in range(10))
                if any(pattern.search(header) for pattern in self.compiled_headers):
                    return True
            except Exception as err:
                logger.warning("Could not read file header", file=file_str, error=str(err))

        return False

    def get_safe_files(self, files: list[Path]) -> list[Path]:
        """Filter list to only safe non-generated files."""
        safe = [file_path for file_path in files if not self.is_generated(file_path)]
        skipped = len(files) - len(safe)
        if skipped:
            logger.info("Filtered generated files", total=len(files), safe=len(safe), skipped=skipped)
        return safe


class SafetyEngine:
    """Assess risk and validate autofix changes."""

    HIGH_RISK_PATTERNS = [
        r"\.env",
        r"\.env\.",
        r"config/production",
        r"config/prod",
        r"secrets",
        r"credentials",
        r"\.key$",
        r"\.pem$",
        r"\.p12$",
        r"\.pfx$",
        r"package\.json$",
        r"pyproject\.toml$",
        r"Cargo\.toml$",
        r"go\.mod$",
        r"pom\.xml$",
        r"build\.gradle$",
        r"Gemfile$",
        r"composer\.json$",
    ]
    MEDIUM_RISK_PATTERNS = [
        r"migrations/",
        r"schema\.sql$",
        r"database\.yml$",
        r"routes\.",
        r"router\.",
        r"\.route\.",
        r"api/",
        r"\.test\.",
        r"\.spec\.",
        r"(^|/)tests?/",
        r"(^|/)test_[^/]+$",
        r"_test\.py$",
    ]

    def __init__(self):
        self.detector = GeneratedFileDetector()
        self.high_risk = [re.compile(pattern, re.IGNORECASE) for pattern in self.HIGH_RISK_PATTERNS]
        self.medium_risk = [re.compile(pattern, re.IGNORECASE) for pattern in self.MEDIUM_RISK_PATTERNS]

    def assess_risk(self, file_path: Path, fix_type: str) -> RiskLevel:
        """Assess the risk level of applying a fix to a file."""
        file_str = file_path.as_posix()

        if self.detector.is_generated(file_path):
            raise ValueError(f"Cannot modify generated file: {file_path}")
        if any(pattern.search(file_str) for pattern in self.high_risk):
            return RiskLevel.HIGH
        if any(pattern.search(file_str) for pattern in self.medium_risk):
            return RiskLevel.MEDIUM

        return {
            "docs_regen": RiskLevel.LOW,
            "link_fix": RiskLevel.LOW,
            "selector_insert": RiskLevel.MEDIUM,
            "i18n_scaffold": RiskLevel.MEDIUM,
            "format_fix": RiskLevel.LOW,
        }.get(fix_type, RiskLevel.MEDIUM)

    def validate_changes(
        self,
        original_content: str,
        new_content: str,
        file_path: Path,
    ) -> ValidationResult:
        """Validate that changes are safe and reasonable."""
        orig_lines = original_content.splitlines()
        new_lines = new_content.splitlines()
        validation: ValidationResult = {
            "safe": True,
            "warnings": [],
            "stats": {
                "original_lines": len(orig_lines),
                "new_lines": len(new_lines),
                "lines_added": len(new_lines) - len(orig_lines),
                "size_change_bytes": len(new_content) - len(original_content),
            },
        }
        warnings = validation["warnings"]

        if len(new_content) > len(original_content) * 2:
            warnings.append("File size doubled - review recommended")
            validation["safe"] = False
        if not new_lines and orig_lines:
            warnings.append("All content removed - blocking change")
            validation["safe"] = False

        important_patterns = [
            (r"@[a-zA-Z]+\(", "decorators"),
            (r"def\s+\w+", "function definitions"),
            (r"class\s+\w+", "class definitions"),
            (r"export\s+(default\s+)?(class|function|const)", "exports"),
        ]
        for pattern, name in important_patterns:
            orig_count = len(re.findall(pattern, original_content))
            new_count = len(re.findall(pattern, new_content))
            if orig_count > new_count:
                warnings.append(f"Reduced {name} from {orig_count} to {new_count}")

        return validation

    def should_skip_file(self, file_path: Path) -> bool:
        return self.detector.is_generated(file_path)

    def get_approval_required(self, risk_level: RiskLevel) -> bool:
        return risk_level in {RiskLevel.MEDIUM, RiskLevel.HIGH}

    def get_skipped_patterns(self) -> dict[str, list[str]]:
        return {
            "generated_patterns": self.detector.GENERATED_PATTERNS,
            "lock_files": self.detector.LOCK_FILES,
            "build_dirs": self.detector.BUILD_DIRS,
            "high_risk_patterns": self.HIGH_RISK_PATTERNS,
            "medium_risk_patterns": self.MEDIUM_RISK_PATTERNS,
        }
